{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adPlaybackEvent","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"playbackEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent","preciseIdentifier":"c:@M@MSAdSDKVideo@E@VideoAdEvent","text":"VideoAdEvent"},{"text":", ","kind":"text"},{"text":"adEventData","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData","kind":"typeIdentifier","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)AdEventData","text":"AdEventData"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdPlayDelegate\/adPlaybackEvent(_:adEventData:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdPlayDelegate"]]},"metadata":{"role":"symbol","externalID":"c:@M@MSAdSDKVideo@objc(pl)VideoAdPlayDelegate(im)adPlaybackEvent:adEventData:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adPlaybackEvent","kind":"identifier"},{"kind":"text","text":"("},{"text":"VideoAdEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@MSAdSDKVideo@E@VideoAdEvent"},{"text":", ","kind":"text"},{"text":"adEventData","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AdEventData","kind":"typeIdentifier","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)AdEventData"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","required":true,"navigatorTitle":[{"kind":"identifier","text":"adPlaybackEvent:adEventData:"}],"symbolKind":"method","title":"adPlaybackEvent(_:adEventData:)","modules":[{"name":"MSAdSDKVideo"}]},"sections":[],"abstract":[{"type":"text","text":"This method is called when a video ad playback event occurs. It provides information about the specific event as well as associated ad data."},{"text":" ","type":"text"},{"type":"text","text":"playbackEvent: A VideoAdEvent enum case representing the event that occurred during video ad playback. Publishers can switch on this event to handle specific cases."},{"type":"text","text":" "},{"type":"text","text":"adEventData: An instance of the AdEventData class containing additional data related to the ad event, such as ad duration, index, and error information."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/videoadplaydelegate\/adplaybackevent(_:adeventdata:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/msadsdkvideo\/videoadplaydelegate\/adplaybackevent(_:adeventdata:)"]}],"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/AdEventData":{"role":"symbol","title":"AdEventData","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData","kind":"symbol","abstract":[{"text":"AdEventData class is designed to encapsulate essential information related to ad events and ad playback. It serves as a data structure to store data about the currently displayed ad, including its duration, position within a sequence, total ad count, click URL upon ad interaction, and any potential error that may occur during ad playback.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdEventData"}],"navigatorTitle":[{"text":"AdEventData","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/adeventdata"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdPlayDelegate":{"title":"VideoAdPlayDelegate","abstract":[{"text":"VideoAdPlayDelegate protocol defines methods that an object can implement to receive and handle video ad playback events. This protocol is typically used to establish a delegate relationship between an ad playback component and another object (such as a view controller) that wants to monitor and respond to events during video ad playback.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"VideoAdPlayDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoAdPlayDelegate"}],"url":"\/documentation\/msadsdkvideo\/videoadplaydelegate","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdPlayDelegate","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent":{"abstract":[],"title":"VideoAdEvent","role":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent","url":"\/documentation\/msadsdkvideo\/videoadevent","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoAdEvent","kind":"identifier"}],"navigatorTitle":[{"text":"VideoAdEvent","kind":"identifier"}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdPlayDelegate/adPlaybackEvent(_:adEventData:)":{"url":"\/documentation\/msadsdkvideo\/videoadplaydelegate\/adplaybackevent(_:adeventdata:)","required":true,"role":"symbol","navigatorTitle":[{"text":"adPlaybackEvent:adEventData:","kind":"identifier"}],"title":"adPlaybackEvent(_:adEventData:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdPlayDelegate\/adPlaybackEvent(_:adEventData:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adPlaybackEvent","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@MSAdSDKVideo@E@VideoAdEvent","text":"VideoAdEvent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"adEventData","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)AdEventData","text":"AdEventData","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"text":"This method is called when a video ad playback event occurs. It provides information about the specific event as well as associated ad data.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"playbackEvent: A VideoAdEvent enum case representing the event that occurred during video ad playback. Publishers can switch on this event to handle specific cases."},{"text":" ","type":"text"},{"type":"text","text":"adEventData: An instance of the AdEventData class containing additional data related to the ad event, such as ad duration, index, and error information."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"adPlaybackEvent:adEventData:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adPlaybackEvent:adEventData:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"adPlaybackEvent:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@MSAdSDKVideo@E@VideoAdEvent","text":"VideoAdEvent"},{"text":") ","kind":"text"},{"text":"playbackEvent","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adEventData:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)AdEventData","text":"AdEventData"},{"text":" *) ","kind":"text"},{"text":"adEventData","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"value":"AdEventData","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdEventData\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdEventData\/fragments","value":[{"text":"AdEventData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdPlayDelegate\/title","value":"VideoAdPlayDelegate","op":"replace"},{"value":[{"text":"VideoAdPlayDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdPlayDelegate\/fragments","op":"replace"},{"op":"replace","value":"VideoAdEvent","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent\/title"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent\/fragments","op":"replace","value":[{"text":"VideoAdEvent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdPlayDelegate~1adPlaybackEvent(_:adEventData:)\/title","value":"adPlaybackEvent:adEventData:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"adPlaybackEvent:adEventData:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdPlayDelegate~1adPlaybackEvent(_:adEventData:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}