{"abstract":[{"type":"text","text":"EMPTY_REQUEST_URL Signifying an issue with the ad request, this error suggests that the request URL is empty or not set."}],"metadata":{"roleHeading":"Case","externalID":"c:@M@MSAdSDKVideo@E@ErrorMessageConstant@ErrorMessageConstantEMPTY_REQUEST_URL","modules":[{"name":"MSAdSDKVideo"}],"title":"ErrorMessageConstant.EMPTY_REQUEST_URL","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EMPTY_REQUEST_URL"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorMessageConstantEMPTY_REQUEST_URL"}],"symbolKind":"case","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/errormessageconstant\/empty_request_url"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/msadsdkvideo\/errormessageconstant\/empty_request_url"]}],"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/EMPTY_REQUEST_URL"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EMPTY_REQUEST_URL"}],"languages":["swift"]}]}],"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","kind":"symbol","role":"collection","type":"topic","abstract":[],"title":"MSAdSDKVideo","url":"\/documentation\/msadsdkvideo"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorMessageConstant"}],"type":"topic","title":"ErrorMessageConstant","abstract":[{"type":"text","text":"“ErrorMessageConstant” is an enumeration that serves as a list of constants responsible for managing error for Ad Request"}],"navigatorTitle":[{"text":"ErrorMessageConstant","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/errormessageconstant"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant/EMPTY_REQUEST_URL":{"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"ErrorMessageConstantEMPTY_REQUEST_URL","kind":"identifier"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/EMPTY_REQUEST_URL","url":"\/documentation\/msadsdkvideo\/errormessageconstant\/empty_request_url","abstract":[{"type":"text","text":"EMPTY_REQUEST_URL Signifying an issue with the ad request, this error suggests that the request URL is empty or not set."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EMPTY_REQUEST_URL"}],"title":"ErrorMessageConstant.EMPTY_REQUEST_URL"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"ErrorMessageConstantEMPTY_REQUEST_URL","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ErrorMessageConstantEMPTY_REQUEST_URL","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ErrorMessageConstantEMPTY_REQUEST_URL"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant\/title","value":"ErrorMessageConstant"},{"value":[{"kind":"identifier","text":"ErrorMessageConstant"}],"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant\/fragments"},{"value":"ErrorMessageConstantEMPTY_REQUEST_URL","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1EMPTY_REQUEST_URL\/title"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1EMPTY_REQUEST_URL\/fragments","op":"replace","value":[{"text":"ErrorMessageConstantEMPTY_REQUEST_URL","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}