{"identifier":{"url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/EMPTY_URL_LIST","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","title":"ErrorMessageConstant.EMPTY_URL_LIST","externalID":"c:@M@MSAdSDKVideo@E@ErrorMessageConstant@ErrorMessageConstantEMPTY_URL_LIST","symbolKind":"case","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"EMPTY_URL_LIST","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorMessageConstantEMPTY_URL_LIST"}],"modules":[{"name":"MSAdSDKVideo"}]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EMPTY_URL_LIST","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/msadsdkvideo\/errormessageconstant\/empty_url_list"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/msadsdkvideo\/errormessageconstant\/empty_url_list"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"EMPTY_URL_LIST error arises when a list of URLs, which is expected to contain specific content references, is found to be empty.","type":"text"}],"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant/EMPTY_URL_LIST":{"abstract":[{"text":"EMPTY_URL_LIST error arises when a list of URLs, which is expected to contain specific content references, is found to be empty.","type":"text"}],"title":"ErrorMessageConstant.EMPTY_URL_LIST","role":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/EMPTY_URL_LIST","url":"\/documentation\/msadsdkvideo\/errormessageconstant\/empty_url_list","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EMPTY_URL_LIST","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorMessageConstantEMPTY_URL_LIST"}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorMessageConstant"}],"type":"topic","title":"ErrorMessageConstant","abstract":[{"type":"text","text":"“ErrorMessageConstant” is an enumeration that serves as a list of constants responsible for managing error for Ad Request"}],"navigatorTitle":[{"text":"ErrorMessageConstant","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/errormessageconstant"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ErrorMessageConstantEMPTY_URL_LIST","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"ErrorMessageConstantEMPTY_URL_LIST"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"ErrorMessageConstantEMPTY_URL_LIST","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1EMPTY_URL_LIST\/title","value":"ErrorMessageConstantEMPTY_URL_LIST"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1EMPTY_URL_LIST\/fragments","value":[{"text":"ErrorMessageConstantEMPTY_URL_LIST","kind":"identifier"}]},{"value":"ErrorMessageConstant","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorMessageConstant"}]}]}]}