{"variants":[{"paths":["\/documentation\/msadsdkvideo\/errormessageconstant\/failed_to_load_ad"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/msadsdkvideo\/errormessageconstant\/failed_to_load_ad"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"ErrorMessageConstantFAILED_TO_LOAD_AD","kind":"identifier"}],"title":"ErrorMessageConstant.FAILED_TO_LOAD_AD","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FAILED_TO_LOAD_AD","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"MSAdSDKVideo"}],"symbolKind":"case","role":"symbol","externalID":"c:@M@MSAdSDKVideo@E@ErrorMessageConstant@ErrorMessageConstantFAILED_TO_LOAD_AD"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/FAILED_TO_LOAD_AD","interfaceLanguage":"swift"},"abstract":[{"text":"FAILED_TO_LOAD_AD error denotes a failure in loading the ad, typically due to issues with ad retrieval or rendering.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FAILED_TO_LOAD_AD"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant"]]},"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant/FAILED_TO_LOAD_AD":{"navigatorTitle":[{"text":"ErrorMessageConstantFAILED_TO_LOAD_AD","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/errormessageconstant\/failed_to_load_ad","title":"ErrorMessageConstant.FAILED_TO_LOAD_AD","abstract":[{"text":"FAILED_TO_LOAD_AD error denotes a failure in loading the ad, typically due to issues with ad retrieval or rendering.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"FAILED_TO_LOAD_AD","kind":"identifier"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/FAILED_TO_LOAD_AD","kind":"symbol","role":"symbol","type":"topic"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorMessageConstant"}],"type":"topic","title":"ErrorMessageConstant","abstract":[{"type":"text","text":"“ErrorMessageConstant” is an enumeration that serves as a list of constants responsible for managing error for Ad Request"}],"navigatorTitle":[{"text":"ErrorMessageConstant","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/errormessageconstant"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"ErrorMessageConstantFAILED_TO_LOAD_AD","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ErrorMessageConstantFAILED_TO_LOAD_AD","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"ErrorMessageConstantFAILED_TO_LOAD_AD","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1FAILED_TO_LOAD_AD\/title","value":"ErrorMessageConstantFAILED_TO_LOAD_AD"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1FAILED_TO_LOAD_AD\/fragments","value":[{"text":"ErrorMessageConstantFAILED_TO_LOAD_AD","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant\/title","value":"ErrorMessageConstant"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant\/fragments","value":[{"kind":"identifier","text":"ErrorMessageConstant"}]}]}]}