{"abstract":[{"type":"text","text":"INVALID_REQUEST error signifies that the ad request is invalid, possibly due to missing or incorrect parameters"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"INVALID_REQUEST","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/INVALID_REQUEST","interfaceLanguage":"swift"},"metadata":{"role":"symbol","externalID":"c:@M@MSAdSDKVideo@E@ErrorMessageConstant@ErrorMessageConstantINVALID_REQUEST","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"INVALID_REQUEST","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"text":"ErrorMessageConstantINVALID_REQUEST","kind":"identifier"}],"symbolKind":"case","title":"ErrorMessageConstant.INVALID_REQUEST","modules":[{"name":"MSAdSDKVideo"}]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/errormessageconstant\/invalid_request"]},{"paths":["\/documentation\/msadsdkvideo\/errormessageconstant\/invalid_request"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant/INVALID_REQUEST":{"role":"symbol","abstract":[{"text":"INVALID_REQUEST error signifies that the ad request is invalid, possibly due to missing or incorrect parameters","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"INVALID_REQUEST","kind":"identifier"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/INVALID_REQUEST","navigatorTitle":[{"kind":"identifier","text":"ErrorMessageConstantINVALID_REQUEST"}],"url":"\/documentation\/msadsdkvideo\/errormessageconstant\/invalid_request","kind":"symbol","title":"ErrorMessageConstant.INVALID_REQUEST","type":"topic"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorMessageConstant"}],"type":"topic","title":"ErrorMessageConstant","abstract":[{"type":"text","text":"“ErrorMessageConstant” is an enumeration that serves as a list of constants responsible for managing error for Ad Request"}],"navigatorTitle":[{"text":"ErrorMessageConstant","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/errormessageconstant"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"ErrorMessageConstantINVALID_REQUEST","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ErrorMessageConstantINVALID_REQUEST"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"ErrorMessageConstantINVALID_REQUEST","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1INVALID_REQUEST\/title","value":"ErrorMessageConstantINVALID_REQUEST"},{"value":[{"text":"ErrorMessageConstantINVALID_REQUEST","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1INVALID_REQUEST\/fragments"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant\/title","value":"ErrorMessageConstant","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant\/fragments","value":[{"text":"ErrorMessageConstant","kind":"identifier"}]}]}]}