{"metadata":{"modules":[{"name":"MSAdSDKVideo"}],"title":"ErrorMessageConstant.NO_BID","role":"symbol","externalID":"c:@M@MSAdSDKVideo@E@ErrorMessageConstant@ErrorMessageConstantNO_BID","navigatorTitle":[{"text":"ErrorMessageConstantNO_BID","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"NO_BID","kind":"identifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"NO_BID","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/msadsdkvideo\/errormessageconstant\/no_bid"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/msadsdkvideo\/errormessageconstant\/no_bid"]}],"kind":"symbol","abstract":[{"type":"text","text":"NO_BID error where there are no ad bids available, this error is raised, indicating a lack of ad willing to display ads."}],"identifier":{"url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/NO_BID","interfaceLanguage":"swift"},"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant/NO_BID":{"type":"topic","role":"symbol","title":"ErrorMessageConstant.NO_BID","url":"\/documentation\/msadsdkvideo\/errormessageconstant\/no_bid","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"NO_BID","kind":"identifier"}],"abstract":[{"text":"NO_BID error where there are no ad bids available, this error is raised, indicating a lack of ad willing to display ads.","type":"text"}],"navigatorTitle":[{"text":"ErrorMessageConstantNO_BID","kind":"identifier"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/NO_BID"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorMessageConstant"}],"type":"topic","title":"ErrorMessageConstant","abstract":[{"type":"text","text":"“ErrorMessageConstant” is an enumeration that serves as a list of constants responsible for managing error for Ad Request"}],"navigatorTitle":[{"text":"ErrorMessageConstant","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/errormessageconstant"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ErrorMessageConstantNO_BID"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"ErrorMessageConstantNO_BID","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ErrorMessageConstantNO_BID","kind":"identifier"}]}],"kind":"declarations"}},{"value":"ErrorMessageConstantNO_BID","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1NO_BID\/title","op":"replace"},{"op":"replace","value":[{"text":"ErrorMessageConstantNO_BID","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1NO_BID\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant\/title","value":"ErrorMessageConstant"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant\/fragments","value":[{"text":"ErrorMessageConstant","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}