{"kind":"symbol","variants":[{"paths":["\/documentation\/msadsdkvideo\/errormessageconstant\/no_view_found_to_play_ad"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/msadsdkvideo\/errormessageconstant\/no_view_found_to_play_ad"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/NO_VIEW_FOUND_TO_PLAY_AD"},"abstract":[{"type":"text","text":"NO_VIEW_FOUND_TO_PLAY_AD error occurs when there is no suitable view or location available to play the ad."}],"metadata":{"role":"symbol","symbolKind":"case","externalID":"c:@M@MSAdSDKVideo@E@ErrorMessageConstant@ErrorMessageConstantNO_VIEW_FOUND_TO_PLAY_AD","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"NO_VIEW_FOUND_TO_PLAY_AD"}],"modules":[{"name":"MSAdSDKVideo"}],"roleHeading":"Case","navigatorTitle":[{"text":"ErrorMessageConstantNO_VIEW_FOUND_TO_PLAY_AD","kind":"identifier"}],"title":"ErrorMessageConstant.NO_VIEW_FOUND_TO_PLAY_AD"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"NO_VIEW_FOUND_TO_PLAY_AD"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant/NO_VIEW_FOUND_TO_PLAY_AD":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/NO_VIEW_FOUND_TO_PLAY_AD","type":"topic","abstract":[{"text":"NO_VIEW_FOUND_TO_PLAY_AD error occurs when there is no suitable view or location available to play the ad.","type":"text"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NO_VIEW_FOUND_TO_PLAY_AD"}],"url":"\/documentation\/msadsdkvideo\/errormessageconstant\/no_view_found_to_play_ad","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorMessageConstantNO_VIEW_FOUND_TO_PLAY_AD"}],"title":"ErrorMessageConstant.NO_VIEW_FOUND_TO_PLAY_AD"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorMessageConstant"}],"type":"topic","title":"ErrorMessageConstant","abstract":[{"type":"text","text":"“ErrorMessageConstant” is an enumeration that serves as a list of constants responsible for managing error for Ad Request"}],"navigatorTitle":[{"text":"ErrorMessageConstant","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/errormessageconstant"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ErrorMessageConstantNO_VIEW_FOUND_TO_PLAY_AD"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ErrorMessageConstantNO_VIEW_FOUND_TO_PLAY_AD","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ErrorMessageConstantNO_VIEW_FOUND_TO_PLAY_AD","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1NO_VIEW_FOUND_TO_PLAY_AD\/title","value":"ErrorMessageConstantNO_VIEW_FOUND_TO_PLAY_AD"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1NO_VIEW_FOUND_TO_PLAY_AD\/fragments","value":[{"text":"ErrorMessageConstantNO_VIEW_FOUND_TO_PLAY_AD","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant\/title","op":"replace","value":"ErrorMessageConstant"},{"op":"replace","value":[{"text":"ErrorMessageConstant","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}