{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/adeventdata"]},{"paths":["\/documentation\/msadsdkvideo\/adeventdata"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"AdEventData class is designed to encapsulate essential information related to ad events and ad playback. It serves as a data structure to store data about the currently displayed ad, including its duration, position within a sequence, total ad count, click URL upon ad interaction, and any potential error that may occur during ad playback.","type":"text"}],"identifier":{"url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo"]]},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(pl)NSObject","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s7CVarArgP","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s28CustomDebugStringConvertibleP","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s23CustomStringConvertibleP","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SQ","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdEventData"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"title":"AdEventData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AdEventData","kind":"identifier"}],"role":"symbol","externalID":"c:@M@MSAdSDKVideo@objc(cs)AdEventData","navigatorTitle":[{"text":"AdEventData","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"MSAdSDKVideo"}],"symbolKind":"class"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData\/activeAdIndex","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData\/clickURL","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData\/duration","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData\/error","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData\/totalAdCount"]}],"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/s7CVarArgP":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/objc(cs)NSObject":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/AdEventData/error":{"navigatorTitle":[{"kind":"identifier","text":"error"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData\/error","url":"\/documentation\/msadsdkvideo\/adeventdata\/error","role":"symbol","abstract":[{"text":"error property that can store error information if any issues or errors occur during ad playback or interaction. This property is used to capture and handle errors gracefully and may be nil if no errors are encountered.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default Value: nil"},{"text":" ","type":"text"},{"text":"Property type: Optional","type":"text"}],"title":"error","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?","kind":"text"}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/SH":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/AdEventData/totalAdCount":{"title":"totalAdCount","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData\/totalAdCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"totalAdCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"totalAdCount","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents the total number of ads available in the ad sequence or playlist. It provides context about the total count of ads within the sequence."},{"text":" ","type":"text"},{"type":"text","text":"Default Value: 0 which means no ad available"}],"url":"\/documentation\/msadsdkvideo\/adeventdata\/totaladcount","role":"symbol","kind":"symbol","type":"topic"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/AdEventData":{"role":"symbol","title":"AdEventData","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData","kind":"symbol","abstract":[{"text":"AdEventData class is designed to encapsulate essential information related to ad events and ad playback. It serves as a data structure to store data about the currently displayed ad, including its duration, position within a sequence, total ad count, click URL upon ad interaction, and any potential error that may occur during ad playback.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdEventData"}],"navigatorTitle":[{"text":"AdEventData","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/adeventdata"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/objc(pl)NSObject":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/SQ":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/AdEventData/duration":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData\/duration","title":"duration","navigatorTitle":[{"kind":"identifier","text":"duration"}],"url":"\/documentation\/msadsdkvideo\/adeventdata\/duration","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"duration","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"type":"topic","abstract":[{"type":"text","text":"Represents the total time duration of the specified ad in seconds. It provides information about the ad’s duration, indicating how long the current ad will be displayed."},{"type":"text","text":" "},{"type":"text","text":"Default Value: -1 which mean duration not set"}],"kind":"symbol","role":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/AdEventData/clickURL":{"kind":"symbol","title":"clickURL","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clickURL"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"text":"clickURL","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Holds the click URL returned when the user interacts with the ad. This URL typically points to a destination or action triggered upon ad click. It is an optional property that may be nil if no click URL is available."},{"type":"text","text":" "},{"type":"text","text":"Default Value: nil"},{"type":"text","text":" "},{"text":"Property type: Optional","type":"text"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData\/clickURL","url":"\/documentation\/msadsdkvideo\/adeventdata\/clickurl"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/AdEventData/activeAdIndex":{"kind":"symbol","title":"activeAdIndex","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"activeAdIndex","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","navigatorTitle":[{"text":"activeAdIndex","kind":"identifier"}],"type":"topic","abstract":[{"text":"Indicates the index position of the ad that is currently being displayed within a sequence of ads. This property helps track the ad’s position within a playlist or sequence.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default Value: -1 which means no ad loaded"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData\/activeAdIndex","url":"\/documentation\/msadsdkvideo\/adeventdata\/activeadindex"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AdEventData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"AdEventData"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AdEventData"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData\/activeAdIndex","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData\/clickURL","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData\/duration","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData\/error","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData\/totalAdCount"]}]},{"op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(cs)NSObject"],"kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"AdEventData","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"error","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdEventData~1error\/title","op":"replace"},{"op":"replace","value":[{"text":"error","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdEventData~1error\/fragments"},{"op":"replace","value":"totalAdCount","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdEventData~1totalAdCount\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdEventData~1totalAdCount\/fragments","value":[{"text":"totalAdCount","kind":"identifier"}]},{"value":"AdEventData","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdEventData\/title"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdEventData\/fragments","value":[{"kind":"identifier","text":"AdEventData"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdEventData~1duration\/title","value":"duration","op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdEventData~1duration\/fragments","value":[{"text":"duration","kind":"identifier"}],"op":"replace"},{"value":"clickURL","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdEventData~1clickURL\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdEventData~1clickURL\/fragments","value":[{"text":"clickURL","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdEventData~1activeAdIndex\/title","value":"activeAdIndex","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"activeAdIndex"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdEventData~1activeAdIndex\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}