{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo"]]},"topicSections":[{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdResponseData\/data"],"title":"Instance Properties"}],"abstract":[{"text":"AdResponseData class is designed to encapsulate data related to ad responses, particularly for fetching ad content from a URL. This class provides properties for storing the URL of the ad content and any potential errors that may occur during the ad request and retrieval process.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/adresponsedata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/msadsdkvideo\/adresponsedata"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdResponseData"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdResponseData"},"metadata":{"role":"symbol","externalID":"c:@M@MSAdSDKVideo@objc(cs)AdResponseData","title":"AdResponseData","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdResponseData"}],"navigatorTitle":[{"text":"AdResponseData","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"MSAdSDKVideo"}],"symbolKind":"class"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(pl)NSObject","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s7CVarArgP","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s28CustomDebugStringConvertibleP","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s23CustomStringConvertibleP","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SQ","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/AdResponseData":{"title":"AdResponseData","kind":"symbol","url":"\/documentation\/msadsdkvideo\/adresponsedata","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdResponseData"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"AdResponseData","kind":"identifier"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdResponseData","abstract":[{"type":"text","text":"AdResponseData class is designed to encapsulate data related to ad responses, particularly for fetching ad content from a URL. This class provides properties for storing the URL of the ad content and any potential errors that may occur during the ad request and retrieval process."}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/AdResponseData/init":{"abstract":[],"title":"init","type":"topic","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdResponseData\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/adresponsedata\/init","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(pl)NSObject","type":"unresolvable"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s7CVarArgP","type":"unresolvable"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SQ","type":"unresolvable"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/AdResponseData/data":{"navigatorTitle":[{"text":"data","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/adresponsedata\/data","title":"data","abstract":[{"type":"text","text":"the URL from which the ad content can be fetched. This property holds the URL pointing to the location of the ad creative."},{"text":" ","type":"text"},{"type":"text","text":"Default Value: nil"},{"type":"text","text":" "},{"type":"text","text":"Error  that can store  information if any issues or errors occur during the ad request and retrieval process. This property is used to capture and handle errors gracefully and may be nil if no errors are encountered."},{"type":"text","text":" "},{"text":"Property type: Optional","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": ["},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":" : [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]]?","kind":"text"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdResponseData\/data","kind":"symbol","role":"symbol","type":"topic"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SH","type":"unresolvable"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(cs)NSObject","type":"unresolvable"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s28CustomDebugStringConvertibleP"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"AdResponseData","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AdResponseData","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"AdResponseData","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdResponseData\/data"]},{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdResponseData\/init"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(cs)NSObject"]}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdResponseData"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdResponseData\/title","value":"AdResponseData","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdResponseData\/fragments","value":[{"text":"AdResponseData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdResponseData~1data\/title","op":"replace","value":"data"},{"op":"replace","value":[{"text":"data","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdResponseData~1data\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}