{"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"ClickAction’s responsibility is to overseeing and responding to user interactions with Ad."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClickAction"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"MSAdSDKVideo"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ClickAction","kind":"identifier"}],"title":"ClickAction","roleHeading":"Enumeration","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"ClickAction"}],"externalID":"c:@M@MSAdSDKVideo@E@ClickAction","role":"symbol"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction\/openDeviceBrowser","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction\/openSDKBrowser","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction\/returnURL"]},{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction\/rawValue-swift.property"],"title":"Instance Properties"},{"title":"Type Aliases","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction\/RawValue-swift.typealias"]},{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction\/Equatable-Implementations","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction"},"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SQ","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SH","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SY"],"title":"Conforms To"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/clickaction"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/msadsdkvideo\/clickaction"]}],"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo"]]},"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ClickAction":{"title":"ClickAction","abstract":[{"text":"ClickAction’s responsibility is to overseeing and responding to user interactions with Ad.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"ClickAction","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClickAction"}],"url":"\/documentation\/msadsdkvideo\/clickaction","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ClickAction/openDeviceBrowser":{"title":"ClickAction.openDeviceBrowser","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ClickActionOpenDeviceBrowser"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"openDeviceBrowser"}],"url":"\/documentation\/msadsdkvideo\/clickaction\/opendevicebrowser","kind":"symbol","type":"topic","abstract":[{"text":"“openDeviceBrowser” function is responsible for triggering the device’s native web browser when a user interacts with  ad. In this scenario, the user is redirected to web browser, causing them to exit the app.","type":"text"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction\/openDeviceBrowser"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ClickAction/openSDKBrowser":{"navigatorTitle":[{"kind":"identifier","text":"ClickActionOpenSDKBrowser"}],"url":"\/documentation\/msadsdkvideo\/clickaction\/opensdkbrowser","abstract":[{"type":"text","text":"“openSDKBrowser” function is designed to launch an in-app browser within the SDK when a user interacts with an ad"}],"title":"ClickAction.openSDKBrowser","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"openSDKBrowser","kind":"identifier"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction\/openSDKBrowser","kind":"symbol","role":"symbol","type":"topic"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ClickAction/Equatable-Implementations":{"url":"\/documentation\/msadsdkvideo\/clickaction\/equatable-implementations","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction\/Equatable-Implementations","title":"Equatable Implementations","role":"collectionGroup","type":"topic","abstract":[],"kind":"article"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/SY":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ClickAction/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","url":"\/documentation\/msadsdkvideo\/clickaction\/rawrepresentable-implementations","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction\/RawRepresentable-Implementations","type":"topic","abstract":[],"role":"collectionGroup","kind":"article"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ClickAction/init(rawValue:)":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction\/init(rawValue:)","type":"topic","url":"\/documentation\/msadsdkvideo\/clickaction\/init(rawvalue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:12MSAdSDKVideo11ClickActionO8RawValuea","text":"RawValue","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/SQ":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ClickAction/RawValue-swift.typealias":{"navigatorTitle":[{"text":"RawValue","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction\/RawValue-swift.typealias","url":"\/documentation\/msadsdkvideo\/clickaction\/rawvalue-swift.typealias","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RawValue"}],"title":"ClickAction.RawValue"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ClickAction/returnURL":{"role":"symbol","abstract":[{"type":"text","text":"“returnURL” is responsible for provding the URL when user interact with Ad"}],"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"returnURL","kind":"identifier"}],"title":"ClickAction.returnURL","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction\/returnURL","navigatorTitle":[{"kind":"identifier","text":"ClickActionReturnURL"}],"url":"\/documentation\/msadsdkvideo\/clickaction\/returnurl"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ClickAction/rawValue-swift.property":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction\/rawValue-swift.property","url":"\/documentation\/msadsdkvideo\/clickaction\/rawvalue-swift.property","abstract":[],"kind":"symbol","type":"topic","title":"rawValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"rawValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RawValue","preciseIdentifier":"s:12MSAdSDKVideo11ClickActionO8RawValuea","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/SH":{"type":"unresolvable","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"ClickAction"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ClickAction","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"ClickAction"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction\/openDeviceBrowser","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction\/openSDKBrowser","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction\/returnURL"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClickAction"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ClickAction\/title","value":"ClickAction","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ClickAction\/fragments","value":[{"text":"ClickAction","kind":"identifier"}]},{"op":"replace","value":"ClickActionOpenDeviceBrowser","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ClickAction~1openDeviceBrowser\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ClickAction~1openDeviceBrowser\/fragments","value":[{"text":"ClickActionOpenDeviceBrowser","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ClickAction~1openSDKBrowser\/title","value":"ClickActionOpenSDKBrowser","op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ClickAction~1openSDKBrowser\/fragments","op":"replace","value":[{"text":"ClickActionOpenSDKBrowser","kind":"identifier"}]},{"op":"replace","value":"ClickActionReturnURL","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ClickAction~1returnURL\/title"},{"value":[{"text":"ClickActionReturnURL","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ClickAction~1returnURL\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}