{"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/errormessageconstant"]},{"paths":["\/documentation\/msadsdkvideo\/errormessageconstant"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SQ","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SH","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"metadata":{"modules":[{"name":"MSAdSDKVideo"}],"roleHeading":"Enumeration","symbolKind":"enum","externalID":"c:@M@MSAdSDKVideo@E@ErrorMessageConstant","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorMessageConstant","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorMessageConstant"}],"role":"symbol","title":"ErrorMessageConstant"},"abstract":[{"text":"“ErrorMessageConstant” is an enumeration that serves as a list of constants responsible for managing error for Ad Request","type":"text"}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/EMPTY_REQUEST_URL","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/EMPTY_URL_LIST","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/FAILED_TO_LOAD_AD","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/INVALID_REQUEST","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/NETWORK_ERROR","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/NO_BID","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/NO_VIEW_FOUND_TO_PLAY_AD","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/REQUEST_TOO_FREQUENT","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/VIDEO_ERROR"]},{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/init(rawValue:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/rawValue-swift.property"]},{"title":"Type Aliases","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/RawValue-swift.typealias"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/Equatable-Implementations","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/RawRepresentable-Implementations"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorMessageConstant"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant/NETWORK_ERROR":{"navigatorTitle":[{"text":"ErrorMessageConstantNETWORK_ERROR","kind":"identifier"}],"abstract":[{"type":"text","text":"NETWORK_ERROR error is triggered when there are network-related problems, such as connectivity issues or server unavailability."}],"url":"\/documentation\/msadsdkvideo\/errormessageconstant\/network_error","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"NETWORK_ERROR","kind":"identifier"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/NETWORK_ERROR","type":"topic","title":"ErrorMessageConstant.NETWORK_ERROR","kind":"symbol","role":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant/EMPTY_URL_LIST":{"abstract":[{"text":"EMPTY_URL_LIST error arises when a list of URLs, which is expected to contain specific content references, is found to be empty.","type":"text"}],"title":"ErrorMessageConstant.EMPTY_URL_LIST","role":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/EMPTY_URL_LIST","url":"\/documentation\/msadsdkvideo\/errormessageconstant\/empty_url_list","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EMPTY_URL_LIST","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorMessageConstantEMPTY_URL_LIST"}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant/RawValue-swift.typealias":{"role":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/RawValue-swift.typealias","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"RawValue","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RawValue"}],"kind":"symbol","abstract":[],"url":"\/documentation\/msadsdkvideo\/errormessageconstant\/rawvalue-swift.typealias","title":"ErrorMessageConstant.RawValue"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant/REQUEST_TOO_FREQUENT":{"url":"\/documentation\/msadsdkvideo\/errormessageconstant\/request_too_frequent","title":"ErrorMessageConstant.REQUEST_TOO_FREQUENT","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/REQUEST_TOO_FREQUENT","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"REQUEST_TOO_FREQUENT"}],"abstract":[{"type":"text","text":"REQUEST_TOO_FREQUENT error occurs when ad requests are made too frequently, potentially exceeding rate limits"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorMessageConstantREQUEST_TOO_FREQUENT"}],"kind":"symbol","role":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SH"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant/init(rawValue:)":{"kind":"symbol","title":"init(rawValue:)","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/init(rawValue:)","role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RawValue","preciseIdentifier":"s:12MSAdSDKVideo20ErrorMessageConstantO8RawValuea","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/msadsdkvideo\/errormessageconstant\/init(rawvalue:)","abstract":[]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SY"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant/EMPTY_REQUEST_URL":{"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"ErrorMessageConstantEMPTY_REQUEST_URL","kind":"identifier"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/EMPTY_REQUEST_URL","url":"\/documentation\/msadsdkvideo\/errormessageconstant\/empty_request_url","abstract":[{"type":"text","text":"EMPTY_REQUEST_URL Signifying an issue with the ad request, this error suggests that the request URL is empty or not set."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EMPTY_REQUEST_URL"}],"title":"ErrorMessageConstant.EMPTY_REQUEST_URL"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant/NO_VIEW_FOUND_TO_PLAY_AD":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/NO_VIEW_FOUND_TO_PLAY_AD","type":"topic","abstract":[{"text":"NO_VIEW_FOUND_TO_PLAY_AD error occurs when there is no suitable view or location available to play the ad.","type":"text"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NO_VIEW_FOUND_TO_PLAY_AD"}],"url":"\/documentation\/msadsdkvideo\/errormessageconstant\/no_view_found_to_play_ad","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorMessageConstantNO_VIEW_FOUND_TO_PLAY_AD"}],"title":"ErrorMessageConstant.NO_VIEW_FOUND_TO_PLAY_AD"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant/FAILED_TO_LOAD_AD":{"navigatorTitle":[{"text":"ErrorMessageConstantFAILED_TO_LOAD_AD","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/errormessageconstant\/failed_to_load_ad","title":"ErrorMessageConstant.FAILED_TO_LOAD_AD","abstract":[{"text":"FAILED_TO_LOAD_AD error denotes a failure in loading the ad, typically due to issues with ad retrieval or rendering.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"FAILED_TO_LOAD_AD","kind":"identifier"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/FAILED_TO_LOAD_AD","kind":"symbol","role":"symbol","type":"topic"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant/Equatable-Implementations":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/Equatable-Implementations","url":"\/documentation\/msadsdkvideo\/errormessageconstant\/equatable-implementations","kind":"article","type":"topic","abstract":[],"title":"Equatable Implementations","role":"collectionGroup"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant/RawRepresentable-Implementations":{"abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/RawRepresentable-Implementations","type":"topic","url":"\/documentation\/msadsdkvideo\/errormessageconstant\/rawrepresentable-implementations","kind":"article","title":"RawRepresentable Implementations"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant/NO_BID":{"type":"topic","role":"symbol","title":"ErrorMessageConstant.NO_BID","url":"\/documentation\/msadsdkvideo\/errormessageconstant\/no_bid","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"NO_BID","kind":"identifier"}],"abstract":[{"text":"NO_BID error where there are no ad bids available, this error is raised, indicating a lack of ad willing to display ads.","type":"text"}],"navigatorTitle":[{"text":"ErrorMessageConstantNO_BID","kind":"identifier"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/NO_BID"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/SQ":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant/rawValue-swift.property":{"title":"rawValue","kind":"symbol","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/rawValue-swift.property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"rawValue","kind":"identifier"},{"kind":"text","text":": "},{"text":"RawValue","preciseIdentifier":"s:12MSAdSDKVideo20ErrorMessageConstantO8RawValuea","kind":"typeIdentifier"}],"url":"\/documentation\/msadsdkvideo\/errormessageconstant\/rawvalue-swift.property"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorMessageConstant"}],"type":"topic","title":"ErrorMessageConstant","abstract":[{"type":"text","text":"“ErrorMessageConstant” is an enumeration that serves as a list of constants responsible for managing error for Ad Request"}],"navigatorTitle":[{"text":"ErrorMessageConstant","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/errormessageconstant"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant/VIDEO_ERROR":{"role":"symbol","url":"\/documentation\/msadsdkvideo\/errormessageconstant\/video_error","kind":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/VIDEO_ERROR","navigatorTitle":[{"kind":"identifier","text":"ErrorMessageConstantVIDEO_ERROR"}],"abstract":[{"text":"VIDEO_ERROR error indicates a problem with the video content, such as format or playback issues.","type":"text"}],"title":"ErrorMessageConstant.VIDEO_ERROR","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VIDEO_ERROR","kind":"identifier"}],"type":"topic"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant/INVALID_REQUEST":{"role":"symbol","abstract":[{"text":"INVALID_REQUEST error signifies that the ad request is invalid, possibly due to missing or incorrect parameters","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"INVALID_REQUEST","kind":"identifier"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/INVALID_REQUEST","navigatorTitle":[{"kind":"identifier","text":"ErrorMessageConstantINVALID_REQUEST"}],"url":"\/documentation\/msadsdkvideo\/errormessageconstant\/invalid_request","kind":"symbol","title":"ErrorMessageConstant.INVALID_REQUEST","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"ErrorMessageConstant","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorMessageConstant"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ErrorMessageConstant","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/EMPTY_REQUEST_URL","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/EMPTY_URL_LIST","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/FAILED_TO_LOAD_AD","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/INVALID_REQUEST","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/NETWORK_ERROR","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/NO_BID","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/NO_VIEW_FOUND_TO_PLAY_AD","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/REQUEST_TOO_FREQUENT","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant\/VIDEO_ERROR"]}]},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ErrorMessageConstant"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1NETWORK_ERROR\/title","value":"ErrorMessageConstantNETWORK_ERROR"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1NETWORK_ERROR\/fragments","value":[{"kind":"identifier","text":"ErrorMessageConstantNETWORK_ERROR"}]},{"op":"replace","value":"ErrorMessageConstantEMPTY_URL_LIST","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1EMPTY_URL_LIST\/title"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1EMPTY_URL_LIST\/fragments","value":[{"kind":"identifier","text":"ErrorMessageConstantEMPTY_URL_LIST"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1REQUEST_TOO_FREQUENT\/title","value":"ErrorMessageConstantREQUEST_TOO_FREQUENT","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1REQUEST_TOO_FREQUENT\/fragments","value":[{"kind":"identifier","text":"ErrorMessageConstantREQUEST_TOO_FREQUENT"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1EMPTY_REQUEST_URL\/title","value":"ErrorMessageConstantEMPTY_REQUEST_URL"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1EMPTY_REQUEST_URL\/fragments","value":[{"kind":"identifier","text":"ErrorMessageConstantEMPTY_REQUEST_URL"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1NO_VIEW_FOUND_TO_PLAY_AD\/title","value":"ErrorMessageConstantNO_VIEW_FOUND_TO_PLAY_AD"},{"value":[{"text":"ErrorMessageConstantNO_VIEW_FOUND_TO_PLAY_AD","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1NO_VIEW_FOUND_TO_PLAY_AD\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1FAILED_TO_LOAD_AD\/title","value":"ErrorMessageConstantFAILED_TO_LOAD_AD"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1FAILED_TO_LOAD_AD\/fragments","value":[{"kind":"identifier","text":"ErrorMessageConstantFAILED_TO_LOAD_AD"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1NO_BID\/title","value":"ErrorMessageConstantNO_BID"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1NO_BID\/fragments","op":"replace","value":[{"text":"ErrorMessageConstantNO_BID","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant\/title","value":"ErrorMessageConstant","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant\/fragments","value":[{"kind":"identifier","text":"ErrorMessageConstant"}]},{"value":"ErrorMessageConstantVIDEO_ERROR","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1VIDEO_ERROR\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1VIDEO_ERROR\/fragments","value":[{"text":"ErrorMessageConstantVIDEO_ERROR","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1INVALID_REQUEST\/title","value":"ErrorMessageConstantINVALID_REQUEST","op":"replace"},{"op":"replace","value":[{"text":"ErrorMessageConstantINVALID_REQUEST","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant~1INVALID_REQUEST\/fragments"}]}]}