{"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/all","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/debug","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/error","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/info","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/mark","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/trace","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/warn"]},{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/Equatable-Implementations","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SQ","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SH","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SY"],"title":"Conforms To"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo"]]},"metadata":{"navigatorTitle":[{"text":"LogLevel","kind":"identifier"}],"externalID":"c:@M@MSAdSDKVideo@E@LogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"symbolKind":"enum","roleHeading":"Enumeration","role":"symbol","modules":[{"name":"MSAdSDKVideo"}],"title":"LogLevel"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/loglevel"]},{"paths":["\/documentation\/msadsdkvideo\/loglevel"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"LogLevel defines different log levels, each with an associated integer value for fine-tuned control over log verbosity."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"LogLevel","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/LogLevel/debug":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debug"}],"kind":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/debug","url":"\/documentation\/msadsdkvideo\/loglevel\/debug","abstract":[],"title":"LogLevel.debug","navigatorTitle":[{"text":"LogLevelDebug","kind":"identifier"}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/LogLevel/all":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/all","navigatorTitle":[{"text":"LogLevelAll","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"all"}],"abstract":[],"url":"\/documentation\/msadsdkvideo\/loglevel\/all","type":"topic","kind":"symbol","title":"LogLevel.all","role":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SY"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/LogLevel/warn":{"navigatorTitle":[{"kind":"identifier","text":"LogLevelWarn"}],"abstract":[],"url":"\/documentation\/msadsdkvideo\/loglevel\/warn","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"warn","kind":"identifier"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/warn","type":"topic","title":"LogLevel.warn","kind":"symbol","role":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/LogLevel/trace":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trace"}],"title":"LogLevel.trace","navigatorTitle":[{"kind":"identifier","text":"LogLevelTrace"}],"url":"\/documentation\/msadsdkvideo\/loglevel\/trace","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/trace","abstract":[],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/LogLevel/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/init(rawValue:)","kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"url":"\/documentation\/msadsdkvideo\/loglevel\/init(rawvalue:)"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/LogLevel/Equatable-Implementations":{"abstract":[],"url":"\/documentation\/msadsdkvideo\/loglevel\/equatable-implementations","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/Equatable-Implementations","type":"topic","title":"Equatable Implementations","kind":"article","role":"collectionGroup"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SQ"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/LogLevel/info":{"role":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/info","navigatorTitle":[{"text":"LogLevelInfo","kind":"identifier"}],"type":"topic","title":"LogLevel.info","url":"\/documentation\/msadsdkvideo\/loglevel\/info","abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"info","kind":"identifier"}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/LogLevel/mark":{"abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/msadsdkvideo\/loglevel\/mark","title":"LogLevel.mark","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/mark","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mark"}],"navigatorTitle":[{"text":"LogLevelMark","kind":"identifier"}],"kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SH"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/LogLevel":{"title":"LogLevel","abstract":[{"text":"LogLevel defines different log levels, each with an associated integer value for fine-tuned control over log verbosity.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"LogLevel","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"url":"\/documentation\/msadsdkvideo\/loglevel","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/LogLevel/RawRepresentable-Implementations":{"url":"\/documentation\/msadsdkvideo\/loglevel\/rawrepresentable-implementations","abstract":[],"title":"RawRepresentable Implementations","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/RawRepresentable-Implementations","kind":"article","role":"collectionGroup","type":"topic"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/LogLevel/error":{"navigatorTitle":[{"kind":"identifier","text":"LogLevelError"}],"abstract":[],"url":"\/documentation\/msadsdkvideo\/loglevel\/error","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/error","type":"topic","title":"LogLevel.error","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"value":"LogLevel","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LogLevel"}]},{"op":"replace","value":[{"text":"LogLevel","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/all","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/debug","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/error","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/info","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/mark","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/trace","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/warn"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"LogLevel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"LogLevelDebug","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel~1debug\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel~1debug\/fragments","value":[{"kind":"identifier","text":"LogLevelDebug"}]},{"op":"replace","value":"LogLevelAll","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel~1all\/title"},{"value":[{"kind":"identifier","text":"LogLevelAll"}],"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel~1all\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel~1warn\/title","value":"LogLevelWarn"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel~1warn\/fragments","value":[{"text":"LogLevelWarn","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"LogLevelTrace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel~1trace\/title"},{"value":[{"text":"LogLevelTrace","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel~1trace\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel~1info\/title","op":"replace","value":"LogLevelInfo"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel~1info\/fragments","op":"replace","value":[{"kind":"identifier","text":"LogLevelInfo"}]},{"op":"replace","value":"LogLevelMark","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel~1mark\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel~1mark\/fragments","value":[{"text":"LogLevelMark","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel\/title","value":"LogLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel\/fragments","value":[{"kind":"identifier","text":"LogLevel"}]},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel~1error\/title","value":"LogLevelError","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"LogLevelError"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel~1error\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}