{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/msadsdkinstream"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/msadsdkvideo\/msadsdkinstream"]}],"abstract":[{"type":"text","text":"MSAdSDKVideo  ensures that the sdk loads up with the required configuration like userAgent Network Manager"}],"metadata":{"modules":[{"name":"MSAdSDKVideo"}],"title":"MSAdSDKInstream","externalID":"c:@M@MSAdSDKVideo@objc(cs)MSAdSDKInstream","role":"symbol","navigatorTitle":[{"text":"MSAdSDKInstream","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MSAdSDKInstream","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MSAdSDKInstream"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSAdSDKInstream","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSAdSDKInstream\/initialize(preCacheObjects:memberId:completionHandler:)"]},{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSAdSDKInstream\/sharedInstance()"],"title":"Type Methods"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(pl)NSObject","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s7CVarArgP","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s28CustomDebugStringConvertibleP","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s23CustomStringConvertibleP","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SQ","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SH"],"type":"conformsTo"}],"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/SQ":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/objc(cs)NSObject":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSAdSDKInstream/sharedInstance()":{"url":"\/documentation\/msadsdkvideo\/msadsdkinstream\/sharedinstance()","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSAdSDKInstream\/sharedInstance()","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sharedInstance","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MSAdSDKInstream","kind":"typeIdentifier","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)MSAdSDKInstream"}],"type":"topic","abstract":[{"type":"text","text":"sharedInstance method is a static class function that provides access to a shared instance of the MSAdSDKVideo class. the Singleton design pattern, ensuring that there is only one instance of MSAdSDKVideo created and reused across your application’s lifecycle."}],"role":"symbol","navigatorTitle":[{"text":"sharedInstance","kind":"identifier"}],"kind":"symbol","title":"sharedInstance()"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/SH":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSAdSDKInstream/initialize(preCacheObjects:memberId:completionHandler:)":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSAdSDKInstream\/initialize(preCacheObjects:memberId:completionHandler:)","url":"\/documentation\/msadsdkvideo\/msadsdkinstream\/initialize(precacheobjects:memberid:completionhandler:)","title":"initialize(preCacheObjects:memberId:completionHandler:)","abstract":[{"text":"Initiates will allow to enable preCacheObjects to perform preloading of User Agent","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preCacheObjects","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"memberId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"initializeWithPreCacheObjects:memberId:completionHandler:","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSAdSDKInstream":{"title":"MSAdSDKInstream","abstract":[{"text":"MSAdSDKVideo  ensures that the sdk loads up with the required configuration like userAgent Network Manager","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"MSAdSDKInstream","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MSAdSDKInstream"}],"url":"\/documentation\/msadsdkvideo\/msadsdkinstream","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSAdSDKInstream","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/s7CVarArgP":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/objc(pl)NSObject":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"MSAdSDKInstream","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MSAdSDKInstream"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MSAdSDKInstream","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSAdSDKInstream\/initialize(preCacheObjects:memberId:completionHandler:)"],"title":"Instance Methods"},{"title":"Type Methods","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSAdSDKInstream\/sharedInstance()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MSAdSDKInstream"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"sharedInstance","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1MSAdSDKInstream~1sharedInstance()\/title"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1MSAdSDKInstream~1sharedInstance()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sharedInstance","kind":"identifier"}],"op":"replace"},{"value":"initializeWithPreCacheObjects:memberId:completionHandler:","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1MSAdSDKInstream~1initialize(preCacheObjects:memberId:completionHandler:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initializeWithPreCacheObjects:memberId:completionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1MSAdSDKInstream~1initialize(preCacheObjects:memberId:completionHandler:)\/fragments"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1MSAdSDKInstream\/title","value":"MSAdSDKInstream","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1MSAdSDKInstream\/fragments","value":[{"text":"MSAdSDKInstream","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}