{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MSVideoPlayerSettings"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/msvideoplayersettings"]},{"paths":["\/documentation\/msadsdkvideo\/msvideoplayersettings"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(pl)NSObject","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s7CVarArgP","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s28CustomDebugStringConvertibleP","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s23CustomStringConvertibleP","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SQ","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SH"],"type":"conformsTo","title":"Conforms To"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"MSVideoPlayerSettings"}],"title":"MSVideoPlayerSettings","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MSVideoPlayerSettings","kind":"identifier"}],"roleHeading":"Class","role":"symbol","symbolKind":"class","modules":[{"name":"MSAdSDKVideo"}],"externalID":"c:@M@MSAdSDKVideo@objc(cs)MSVideoPlayerSettings"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/adText","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/clickThruText","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/cssSkinURL","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/initalAudio","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/showAdText","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/showClickThruControl","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/showSkip","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/showTopBar","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/showVolumeControl","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/skipDescription","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/skipLabelName","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/skipOffset"]},{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/sharedInstance"],"title":"Type Properties"}],"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSVideoPlayerSettings/skipOffset":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"skipOffset"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"title":"skipOffset","abstract":[{"type":"codeVoice","code":"skipOffset"},{"text":": An integer value that configures the skip offset (in seconds) on the video player. This value determines the time after which the Skip control becomes active, allowing users to skip the advertisement.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/msadsdkvideo\/msvideoplayersettings\/skipoffset","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/skipOffset","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSVideoPlayerSettings/initalAudio":{"url":"\/documentation\/msadsdkvideo\/msvideoplayersettings\/initalaudio","abstract":[],"title":"initalAudio","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initalAudio"},{"kind":"text","text":": "},{"preciseIdentifier":"s:12MSAdSDKVideo21MSInitialAudioSettingO","text":"MSInitialAudioSetting","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/initalAudio","kind":"symbol","role":"symbol","type":"topic"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/SH":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/s7CVarArgP":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSVideoPlayerSettings/cssSkinURL":{"url":"\/documentation\/msadsdkvideo\/msvideoplayersettings\/cssskinurl","abstract":[{"type":"text","text":"cssSkinURL  is used to specify the URL of a custom CSS file that contains style rules to be applied to Ad player. By setting this property, publisher can customize the visual appearance of the component, such as changing colors, fonts, sizes, spacing, and other styling attributes."}],"title":"cssSkinURL","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cssSkinURL"},{"kind":"text","text":": "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/cssSkinURL","kind":"symbol","role":"symbol","type":"topic"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/SQ":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSVideoPlayerSettings/showAdText":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/showAdText","url":"\/documentation\/msadsdkvideo\/msvideoplayersettings\/showadtext","kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"showAdText","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"showAdText","role":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSVideoPlayerSettings/skipDescription":{"role":"symbol","abstract":[{"type":"text","text":"*"},{"code":"skipDescription","type":"codeVoice"},{"type":"text","text":": A string that can be customized to change the description displayed for the Skip control. This text provides additional information or instructions related to the Skip control."}],"kind":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/skipDescription","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"skipDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/msadsdkvideo\/msvideoplayersettings\/skipdescription","title":"skipDescription","type":"topic"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSVideoPlayerSettings/showTopBar":{"url":"\/documentation\/msadsdkvideo\/msvideoplayersettings\/showtopbar","abstract":[{"text":"*","type":"text"},{"type":"codeVoice","code":"showTopBar"},{"type":"text","text":": A Boolean value that determines whether the top bar, containing the ClickThru and Skip controls, is visible. If set to true, the top bar is displayed at the top of the video player."}],"title":"showTopBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"showTopBar","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/showTopBar","kind":"symbol","role":"symbol","type":"topic"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSVideoPlayerSettings/showSkip":{"abstract":[{"text":"*","type":"text"},{"type":"codeVoice","code":"showSkip"},{"text":": A Boolean value that determines whether the Skip control is displayed on the player. If set to true, the Skip control is shown, allowing users to skip the advertisement.","type":"text"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/showSkip","title":"showSkip","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"showSkip"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","url":"\/documentation\/msadsdkvideo\/msvideoplayersettings\/showskip","type":"topic","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSVideoPlayerSettings/skipLabelName":{"url":"\/documentation\/msadsdkvideo\/msvideoplayersettings\/skiplabelname","abstract":[{"type":"codeVoice","code":"skipLabelName"},{"text":": A string that can be customized to change the label name displayed for the Skip control. This text appears as the label for the Skip control, indicating to users that they can skip the advertisement.","type":"text"}],"title":"skipLabelName","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"skipLabelName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/skipLabelName","kind":"symbol","role":"symbol","type":"topic"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSVideoPlayerSettings/clickThruText":{"url":"\/documentation\/msadsdkvideo\/msvideoplayersettings\/clickthrutext","abstract":[],"title":"clickThruText","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clickThruText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/clickThruText","kind":"symbol","role":"symbol","type":"topic"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSVideoPlayerSettings/sharedInstance":{"url":"\/documentation\/msadsdkvideo\/msvideoplayersettings\/sharedinstance","abstract":[],"title":"sharedInstance","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedInstance"},{"text":": ","kind":"text"},{"text":"MSVideoPlayerSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)MSVideoPlayerSettings"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/sharedInstance","kind":"symbol","role":"symbol","type":"topic"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSVideoPlayerSettings":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MSVideoPlayerSettings","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MSVideoPlayerSettings"}],"url":"\/documentation\/msadsdkvideo\/msvideoplayersettings","title":"MSVideoPlayerSettings","type":"topic"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSVideoPlayerSettings/showVolumeControl":{"url":"\/documentation\/msadsdkvideo\/msvideoplayersettings\/showvolumecontrol","abstract":[],"title":"showVolumeControl","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showVolumeControl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/showVolumeControl","kind":"symbol","role":"symbol","type":"topic"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSVideoPlayerSettings/showClickThruControl":{"url":"\/documentation\/msadsdkvideo\/msvideoplayersettings\/showclickthrucontrol","abstract":[],"title":"showClickThruControl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showClickThruControl"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/showClickThruControl","kind":"symbol","role":"symbol","type":"topic"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/objc(cs)NSObject":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSVideoPlayerSettings/adText":{"url":"\/documentation\/msadsdkvideo\/msvideoplayersettings\/adtext","abstract":[],"title":"adText","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings\/adText","kind":"symbol","role":"symbol","type":"topic"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/objc(pl)NSObject":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MSVideoPlayerSettings","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MSVideoPlayerSettings","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MSVideoPlayerSettings"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":null},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MSVideoPlayerSettings"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"MSVideoPlayerSettings","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1MSVideoPlayerSettings\/title"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1MSVideoPlayerSettings\/fragments","value":[{"text":"MSVideoPlayerSettings","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}