{"identifier":{"url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/browserDismissTitle","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/clickAction","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/customUserAgent","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/enableOpenMeasurement","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/enableSDKOptimization"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/sdkVersion()"]},{"title":"Type Methods","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/sharedInstance()"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo"]]},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(pl)NSObject","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s7CVarArgP","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s28CustomDebugStringConvertibleP","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s23CustomStringConvertibleP","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SQ","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"abstract":[{"text":"SDKSettings class is responsible for managing global settings for the SDK that are shared and common between multiple ad requests. It ensures consistency and ease of maintenance by allowing publishers to set these settings in one place, and the SDK uses these settings for all subsequent ad requests.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDKSettings"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/msadsdkvideo\/sdksettings"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/msadsdkvideo\/sdksettings"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDKSettings","kind":"identifier"}],"symbolKind":"class","externalID":"c:@M@MSAdSDKVideo@objc(cs)SDKSettings","title":"SDKSettings","role":"symbol","modules":[{"name":"MSAdSDKVideo"}],"navigatorTitle":[{"kind":"identifier","text":"SDKSettings"}]},"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/SDKSettings/sharedInstance()":{"navigatorTitle":[{"kind":"identifier","text":"sharedInstance"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sharedInstance","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SDKSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)SDKSettings"}],"type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/sharedInstance()","abstract":[{"type":"text","text":"Returns the shared instance of the SDKSettings class."},{"type":"text","text":" "},{"text":"Returns: An instance of SDKSettings.","type":"text"}],"title":"sharedInstance()","url":"\/documentation\/msadsdkvideo\/sdksettings\/sharedinstance()"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/SDKSettings/sdkVersion()":{"navigatorTitle":[{"kind":"identifier","text":"sdkVersion"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sdkVersion","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/sdkVersion()","abstract":[{"text":"sdkVersion method is used to retrieve the version of the SDK currently in use. The version information of the SDK, which can be useful for tracking and documentation purposes.","type":"text"}],"title":"sdkVersion()","url":"\/documentation\/msadsdkvideo\/sdksettings\/sdkversion()"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/SDKSettings":{"title":"SDKSettings","abstract":[{"text":"SDKSettings class is responsible for managing global settings for the SDK that are shared and common between multiple ad requests. It ensures consistency and ease of maintenance by allowing publishers to set these settings in one place, and the SDK uses these settings for all subsequent ad requests.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SDKSettings","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKSettings"}],"url":"\/documentation\/msadsdkvideo\/sdksettings","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(cs)NSObject","type":"unresolvable"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/SDKSettings/browserDismissTitle":{"navigatorTitle":[{"kind":"identifier","text":"browserDismissTitle"}],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"browserDismissTitle"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/browserDismissTitle","abstract":[{"text":"browserDismissTitle property is used to specify the title of the dismiss button for an in-app browser.The button allows users to close or dismiss the in-app browser when they have finished viewing its content. The property allows publishers to customize the text displayed on this dismiss button.","type":"text"},{"text":" ","type":"text"},{"text":"Default Value: “OK”","type":"text"}],"title":"browserDismissTitle","url":"\/documentation\/msadsdkvideo\/sdksettings\/browserdismisstitle"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/SDKSettings/enableOpenMeasurement":{"navigatorTitle":[{"text":"enableOpenMeasurement","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableOpenMeasurement"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/enableOpenMeasurement","abstract":[{"text":"enableOpenMeasurement property determines whether the SDK should support Open Measurement for viewability and verification measurement when playing the ads. Open Measurement is a set of industry standards for measuring viewability and other ad-related metrics. By enabling Open Measurement, publishers and advertisers can ensure that ad viewability and verification measurements are conducted accurately and transparently.","type":"text"},{"text":" ","type":"text"},{"text":"Default Value: true","type":"text"}],"title":"enableOpenMeasurement","url":"\/documentation\/msadsdkvideo\/sdksettings\/enableopenmeasurement"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/SDKSettings/customUserAgent":{"navigatorTitle":[{"kind":"identifier","text":"customUserAgent"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"customUserAgent"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/customUserAgent","abstract":[{"text":"customUserAgent property is a configuration option in an SDK that allows publishers to specify a custom User-Agent string for the SDK to use. By setting the property, publisher can override the User-Agent string that the SDK fetch from a WebView","type":"text"},{"text":" ","type":"text"},{"text":"If a custom User-Agent string is provided (not nil), the SDK will use this provided string as the User-Agent for all HTTP requests made by the SDK.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default Value: nil"}],"title":"customUserAgent","url":"\/documentation\/msadsdkvideo\/sdksettings\/customuseragent"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s28CustomDebugStringConvertibleP"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SH"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s23CustomStringConvertibleP"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/SDKSettings/init":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/init","abstract":[],"title":"init","url":"\/documentation\/msadsdkvideo\/sdksettings\/init"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SQ"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(pl)NSObject"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/SDKSettings/enableSDKOptimization":{"navigatorTitle":[{"kind":"identifier","text":"enableSDKOptimization"}],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableSDKOptimization"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/enableSDKOptimization","abstract":[{"type":"text","text":"enableSDKOptimization:  the optimization settings for a web view preloading within the SDK."},{"type":"text","text":" "},{"text":"Disabling the SDK optimization may lead to slower initial loading times for web view content.","type":"text"}],"title":"enableSDKOptimization","url":"\/documentation\/msadsdkvideo\/sdksettings\/enablesdkoptimization"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/SDKSettings/clickAction":{"navigatorTitle":[{"text":"clickAction","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"clickAction","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MSAdSDKVideo@E@ClickAction","kind":"typeIdentifier","text":"ClickAction"}],"type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/clickAction","abstract":[{"text":"clickAction property allows publisher to define the behavior of the SDK when a user interacts with the ad. This property offers three distinct options, each of which defines how the SDK should handle the click-through URL associated with the ad.","type":"text"}],"title":"clickAction","url":"\/documentation\/msadsdkvideo\/sdksettings\/clickaction"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/s7CVarArgP":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"SDKSettings","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SDKSettings"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SDKSettings","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/browserDismissTitle","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/clickAction","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/customUserAgent","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/enableOpenMeasurement","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/enableSDKOptimization"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/init","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/sdkVersion()"]},{"title":"Type Methods","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/sharedInstance()"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKSettings"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings~1sharedInstance()\/title","value":"sharedInstance","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"sharedInstance","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings~1sharedInstance()\/fragments"},{"value":"sdkVersion","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings~1sdkVersion()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings~1sdkVersion()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sdkVersion"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings\/title","value":"SDKSettings"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDKSettings"}]},{"value":"browserDismissTitle","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings~1browserDismissTitle\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings~1browserDismissTitle\/fragments","value":[{"kind":"identifier","text":"browserDismissTitle"}]},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings~1enableOpenMeasurement\/title","value":"enableOpenMeasurement","op":"replace"},{"op":"replace","value":[{"text":"enableOpenMeasurement","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings~1enableOpenMeasurement\/fragments"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings~1customUserAgent\/title","value":"customUserAgent","op":"replace"},{"value":[{"kind":"identifier","text":"customUserAgent"}],"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings~1customUserAgent\/fragments"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings~1enableSDKOptimization\/title","op":"replace","value":"enableSDKOptimization"},{"value":[{"kind":"identifier","text":"enableSDKOptimization"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings~1enableSDKOptimization\/fragments","op":"replace"},{"value":"clickAction","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings~1clickAction\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings~1clickAction\/fragments","value":[{"kind":"identifier","text":"clickAction"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}