{"identifier":{"url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/videoadevent"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/msadsdkvideo\/videoadevent"]}],"metadata":{"roleHeading":"Enumeration","title":"VideoAdEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoAdEvent"}],"navigatorTitle":[{"text":"VideoAdEvent","kind":"identifier"}],"modules":[{"name":"MSAdSDKVideo"}],"role":"symbol","symbolKind":"enum","externalID":"c:@M@MSAdSDKVideo@E@VideoAdEvent"},"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo"]]},"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SQ","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SH","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SY"]}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/adDidLeaveApplication","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/adWasClick","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/adWillLeaveApplication","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/allAdsCompleted","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/error","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/firstQuartile","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/fourthQuartile","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/midQuartile","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/muteOff","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/muteOn","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/playStarted","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/readyToPlay","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/returnURL","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/skipped","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/thirdQuartile"]},{"title":"Initializers","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/rawValue-swift.property"],"title":"Instance Properties"},{"title":"Type Aliases","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/RawValue-swift.typealias"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/Equatable-Implementations","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/RawRepresentable-Implementations"],"generated":true}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoAdEvent"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent/thirdQuartile":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"thirdQuartile"}],"type":"topic","kind":"symbol","url":"\/documentation\/msadsdkvideo\/videoadevent\/thirdquartile","role":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/thirdQuartile","title":"VideoAdEvent.thirdQuartile","navigatorTitle":[{"text":"VideoAdEventThirdQuartile","kind":"identifier"}],"abstract":[{"type":"text","text":"Marks the event when the video ad has reached the third quartile of playback."}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/SH":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent/init(rawValue:)":{"abstract":[],"title":"init(rawValue:)","role":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/init(rawValue:)","url":"\/documentation\/msadsdkvideo\/videoadevent\/init(rawvalue:)","type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:12MSAdSDKVideo12VideoAdEventO8RawValuea","text":"RawValue","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent/readyToPlay":{"abstract":[{"text":"Signifies that the video ad is ready to play.","type":"text"}],"title":"VideoAdEvent.readyToPlay","role":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/readyToPlay","url":"\/documentation\/msadsdkvideo\/videoadevent\/readytoplay","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"readyToPlay","kind":"identifier"}],"navigatorTitle":[{"text":"VideoAdEventReadyToPlay","kind":"identifier"}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent/RawValue-swift.typealias":{"abstract":[],"title":"VideoAdEvent.RawValue","role":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/RawValue-swift.typealias","url":"\/documentation\/msadsdkvideo\/videoadevent\/rawvalue-swift.typealias","type":"topic","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RawValue","kind":"identifier"}],"navigatorTitle":[{"text":"RawValue","kind":"identifier"}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent/error":{"abstract":[{"type":"text","text":"Indicates that an error has occurred during ad playback."}],"title":"VideoAdEvent.error","role":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/error","url":"\/documentation\/msadsdkvideo\/videoadevent\/error","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"navigatorTitle":[{"text":"VideoAdEventError","kind":"identifier"}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent/adWillLeaveApplication":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/adWillLeaveApplication","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adWillLeaveApplication"}],"type":"topic","title":"VideoAdEvent.adWillLeaveApplication","abstract":[{"text":"Indicates that the ad will leave the application, typically when clicking on the ad.","type":"text"}],"navigatorTitle":[{"text":"VideoAdEventAdWillLeaveApplication","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/videoadevent\/adwillleaveapplication"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent/adWasClick":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/adWasClick","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adWasClick"}],"type":"topic","abstract":[{"type":"text","text":"Signifies that the ad was clicked, indicating user interaction."}],"title":"VideoAdEvent.adWasClick","navigatorTitle":[{"text":"VideoAdEventAdWasClick","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/videoadevent\/adwasclick"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent/allAdsCompleted":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Indicates that all ads in the sequence have been completed."}],"url":"\/documentation\/msadsdkvideo\/videoadevent\/alladscompleted","title":"VideoAdEvent.allAdsCompleted","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/allAdsCompleted","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"allAdsCompleted"}],"navigatorTitle":[{"text":"VideoAdEventAllAdsCompleted","kind":"identifier"}],"kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent/firstQuartile":{"title":"VideoAdEvent.firstQuartile","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firstQuartile","kind":"identifier"}],"navigatorTitle":[{"text":"VideoAdEventFirstQuartile","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/videoadevent\/firstquartile","kind":"symbol","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/firstQuartile","abstract":[{"text":"Marks the event when the video ad has reached the first quartile of playback.","type":"text"}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent/muteOff":{"title":"VideoAdEvent.muteOff","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"muteOff","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"VideoAdEventMuteOff"}],"url":"\/documentation\/msadsdkvideo\/videoadevent\/muteoff","kind":"symbol","abstract":[{"type":"text","text":"Signifies that the mute setting for the video ad has been turned off."}],"type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/muteOff"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent/playStarted":{"title":"VideoAdEvent.playStarted","role":"symbol","navigatorTitle":[{"text":"VideoAdEventPlayStarted","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"playStarted","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/videoadevent\/playstarted","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Indicates that video ad playback has started."}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/playStarted"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent/skipped":{"title":"VideoAdEvent.skipped","role":"symbol","navigatorTitle":[{"text":"VideoAdEventSkipped","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"skipped"}],"url":"\/documentation\/msadsdkvideo\/videoadevent\/skipped","kind":"symbol","abstract":[{"type":"text","text":"Marks the event when the video ad has been skipped."}],"type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/skipped"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent/Equatable-Implementations":{"title":"Equatable Implementations","role":"collectionGroup","url":"\/documentation\/msadsdkvideo\/videoadevent\/equatable-implementations","kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/Equatable-Implementations"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent/returnURL":{"title":"VideoAdEvent.returnURL","role":"symbol","navigatorTitle":[{"text":"VideoAdEventReturnURL","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"returnURL","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/videoadevent\/returnurl","kind":"symbol","abstract":[{"type":"text","text":"Represents the case when a URL is returned as part of ad interaction. This URL is assumed to be handled by the caller."}],"type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/returnURL"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SY"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent":{"abstract":[],"title":"VideoAdEvent","role":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent","url":"\/documentation\/msadsdkvideo\/videoadevent","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoAdEvent","kind":"identifier"}],"navigatorTitle":[{"text":"VideoAdEvent","kind":"identifier"}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SQ"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent/muteOn":{"title":"VideoAdEvent.muteOn","role":"symbol","navigatorTitle":[{"text":"VideoAdEventMuteOn","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"muteOn"}],"url":"\/documentation\/msadsdkvideo\/videoadevent\/muteon","kind":"symbol","type":"topic","abstract":[{"text":"Signifies that the mute setting for the video ad has been turned on.","type":"text"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/muteOn"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/msadsdkvideo\/videoadevent\/rawrepresentable-implementations","kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/RawRepresentable-Implementations"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent/midQuartile":{"title":"VideoAdEvent.midQuartile","role":"symbol","navigatorTitle":[{"text":"VideoAdEventMidQuartile","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"midQuartile","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/videoadevent\/midquartile","kind":"symbol","type":"topic","abstract":[{"text":"Marks the event when the video ad has reached the mid-quartile of playback.","type":"text"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/midQuartile"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent/adDidLeaveApplication":{"title":"VideoAdEvent.adDidLeaveApplication","role":"symbol","navigatorTitle":[{"text":"VideoAdEventAdDidLeaveApplication","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adDidLeaveApplication"}],"url":"\/documentation\/msadsdkvideo\/videoadevent\/addidleaveapplication","kind":"symbol","abstract":[{"text":"Marks the event when the ad has left the application.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/adDidLeaveApplication"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent/rawValue-swift.property":{"title":"rawValue","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"rawValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:12MSAdSDKVideo12VideoAdEventO8RawValuea","text":"RawValue","kind":"typeIdentifier"}],"url":"\/documentation\/msadsdkvideo\/videoadevent\/rawvalue-swift.property","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/rawValue-swift.property"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent/fourthQuartile":{"title":"VideoAdEvent.fourthQuartile","role":"symbol","navigatorTitle":[{"text":"VideoAdEventFourthQuartile","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fourthQuartile"}],"url":"\/documentation\/msadsdkvideo\/videoadevent\/fourthquartile","kind":"symbol","abstract":[{"type":"text","text":"Marks the event when the video ad has reached the fourth quartile of playback."}],"type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/fourthQuartile"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"value":"VideoAdEvent","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"VideoAdEvent"}]},{"value":[{"kind":"identifier","text":"VideoAdEvent"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/adDidLeaveApplication","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/adWasClick","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/adWillLeaveApplication","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/allAdsCompleted","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/error","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/firstQuartile","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/fourthQuartile","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/midQuartile","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/muteOff","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/muteOn","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/playStarted","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/readyToPlay","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/returnURL","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/skipped","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/thirdQuartile"],"title":"Enumeration Cases"}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoAdEvent","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1thirdQuartile\/title","value":"VideoAdEventThirdQuartile","op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1thirdQuartile\/fragments","value":[{"text":"VideoAdEventThirdQuartile","kind":"identifier"}],"op":"replace"},{"value":"VideoAdEventReadyToPlay","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1readyToPlay\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1readyToPlay\/fragments","op":"replace","value":[{"text":"VideoAdEventReadyToPlay","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1error\/title","value":"VideoAdEventError"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1error\/fragments","op":"replace","value":[{"text":"VideoAdEventError","kind":"identifier"}]},{"value":"VideoAdEventAdWillLeaveApplication","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1adWillLeaveApplication\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1adWillLeaveApplication\/fragments","value":[{"text":"VideoAdEventAdWillLeaveApplication","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1adWasClick\/title","value":"VideoAdEventAdWasClick"},{"value":[{"kind":"identifier","text":"VideoAdEventAdWasClick"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1adWasClick\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1allAdsCompleted\/title","value":"VideoAdEventAllAdsCompleted","op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1allAdsCompleted\/fragments","op":"replace","value":[{"text":"VideoAdEventAllAdsCompleted","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1firstQuartile\/title","value":"VideoAdEventFirstQuartile","op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1firstQuartile\/fragments","value":[{"kind":"identifier","text":"VideoAdEventFirstQuartile"}],"op":"replace"},{"value":"VideoAdEventMuteOff","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1muteOff\/title"},{"value":[{"text":"VideoAdEventMuteOff","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1muteOff\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1playStarted\/title","value":"VideoAdEventPlayStarted"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1playStarted\/fragments","value":[{"kind":"identifier","text":"VideoAdEventPlayStarted"}],"op":"replace"},{"op":"replace","value":"VideoAdEventSkipped","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1skipped\/title"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1skipped\/fragments","value":[{"text":"VideoAdEventSkipped","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1returnURL\/title","op":"replace","value":"VideoAdEventReturnURL"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1returnURL\/fragments","value":[{"text":"VideoAdEventReturnURL","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent\/title","value":"VideoAdEvent","op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent\/fragments","value":[{"kind":"identifier","text":"VideoAdEvent"}],"op":"replace"},{"value":"VideoAdEventMuteOn","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1muteOn\/title"},{"op":"replace","value":[{"kind":"identifier","text":"VideoAdEventMuteOn"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1muteOn\/fragments"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1midQuartile\/title","op":"replace","value":"VideoAdEventMidQuartile"},{"value":[{"kind":"identifier","text":"VideoAdEventMidQuartile"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1midQuartile\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1adDidLeaveApplication\/title","value":"VideoAdEventAdDidLeaveApplication","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"VideoAdEventAdDidLeaveApplication"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1adDidLeaveApplication\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1fourthQuartile\/title","value":"VideoAdEventFourthQuartile"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1fourthQuartile\/fragments","value":[{"text":"VideoAdEventFourthQuartile","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}