{"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo"]]},"topicSections":[{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd\/adResponseData","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd\/isReadyToPlayAd"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd\/loadAd(loadDelegate:)","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd\/playAd(videoAdPlayerDelegate:adContainer:)","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd\/reset()"],"title":"Instance Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"VideoAd","kind":"identifier"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","externalID":"c:@M@MSAdSDKVideo@objc(cs)VideoAd","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoAd"}],"roleHeading":"Class","navigatorTitle":[{"text":"VideoAd","kind":"identifier"}],"symbolKind":"class","title":"VideoAd","modules":[{"name":"MSAdSDKVideo"}]},"variants":[{"paths":["\/documentation\/msadsdkvideo\/videoad"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/msadsdkvideo\/videoad"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdTagProperties"],"title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(pl)NSObject","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s7CVarArgP","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s28CustomDebugStringConvertibleP","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s23CustomStringConvertibleP","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SQ","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SH"],"kind":"relationships","title":"Conforms To"}],"sections":[],"abstract":[{"text":"VideoAd is allowing publisher to  request, load, and play video ads. VideoAd (Video Ad Request and Playback Handler) is responsible for handling video ad requests and facilitating their playback.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Primary responsibilities include Ad Request, Loading, Player Integration, Event Tracking,  Completion,  Caching and Ad Podding to play multiple Ad."}],"kind":"symbol","references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAd/adResponseData":{"role":"symbol","abstract":[{"type":"text","text":"AdResponseData class is designed to encapsulate data related to ad responses, particularly for fetching ad content from a URL. This class provides properties for storing the URL of the ad content and any potential errors that may occur during the ad request and retrieval process."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adResponseData"},{"text":": ","kind":"text"},{"text":"AdResponseData","kind":"typeIdentifier","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)AdResponseData"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd\/adResponseData","navigatorTitle":[{"text":"adResponseData","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/videoad\/adresponsedata","title":"adResponseData","type":"topic","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/objc(pl)NSObject":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAd/init":{"kind":"symbol","title":"init","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd\/init","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/msadsdkvideo\/videoad\/init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAd/isReadyToPlayAd":{"role":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"isReadyToPlayAd"},{"text":" API allows publishers to check whether an ad is ready to be played","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isReadyToPlayAd","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd\/isReadyToPlayAd","navigatorTitle":[{"kind":"identifier","text":"isReadyToPlayAd"}],"url":"\/documentation\/msadsdkvideo\/videoad\/isreadytoplayad","title":"isReadyToPlayAd","type":"topic","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAd/playAd(videoAdPlayerDelegate:adContainer:)":{"title":"playAd(videoAdPlayerDelegate:adContainer:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"playAd","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"videoAdPlayerDelegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"VideoAdPlayDelegate","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(pl)VideoAdPlayDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"adContainer"},{"kind":"text","text":": "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"playAdWithVideoAdPlayerDelegate:adContainer:","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/videoad\/playad(videoadplayerdelegate:adcontainer:)","type":"topic","abstract":[{"text":"playAd(videoAdPlayerDelegate:adContainer:) method is used to play a previously loaded ad. It also includes a delegate that conforms to the VideoAdPlayDelegate protocol to handle ad playback callbacks.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd\/playAd(videoAdPlayerDelegate:adContainer:)"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/AdTagProperties":{"role":"symbol","title":"AdTagProperties","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdTagProperties","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdTagProperties"}],"navigatorTitle":[{"kind":"identifier","text":"AdTagProperties"}],"url":"\/documentation\/msadsdkvideo\/adtagproperties"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAd/reset()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"reset","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd\/reset()","role":"symbol","abstract":[{"type":"text","text":"reset method is used to perform a cleanup operation on an instance of the VideoAd. Operation  involves reseting  resources associated with the player. This is used  to prepare the player for reuse or to clean up after it has finished its use."}],"type":"topic","title":"reset()","url":"\/documentation\/msadsdkvideo\/videoad\/reset()","kind":"symbol","navigatorTitle":[{"text":"reset","kind":"identifier"}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s28CustomDebugStringConvertibleP"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SQ"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s7CVarArgP"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAd":{"title":"VideoAd","abstract":[{"text":"VideoAd is allowing publisher to  request, load, and play video ads. VideoAd (Video Ad Request and Playback Handler) is responsible for handling video ad requests and facilitating their playback.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Primary responsibilities include Ad Request, Loading, Player Integration, Event Tracking,  Completion,  Caching and Ad Podding to play multiple Ad."}],"role":"symbol","navigatorTitle":[{"text":"VideoAd","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoAd"}],"url":"\/documentation\/msadsdkvideo\/videoad","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/s23CustomStringConvertibleP"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAd/loadAd(loadDelegate:)":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd\/loadAd(loadDelegate:)","type":"topic","abstract":[{"type":"text","text":"loadAd(loadDelegate:) method is used to initiate the loading of a video ad. This method sets a delegate object that conforms to the VideoAdLoadDelegate protocol to receive notifications and handle events related to the ad loading process."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadAd","kind":"identifier"},{"kind":"text","text":"("},{"text":"loadDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(pl)VideoAdLoadDelegate","text":"VideoAdLoadDelegate"},{"text":")","kind":"text"}],"url":"\/documentation\/msadsdkvideo\/videoad\/loadad(loaddelegate:)","role":"symbol","navigatorTitle":[{"text":"loadAdWithLoadDelegate:","kind":"identifier"}],"title":"loadAd(loadDelegate:)"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"VideoAd"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"VideoAd","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"VideoAd"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd\/adResponseData","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd\/isReadyToPlayAd"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd\/init","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd\/loadAd(loadDelegate:)","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd\/playAd(videoAdPlayerDelegate:adContainer:)","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd\/reset()"]}]},{"value":[{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdTagProperties"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"VideoAd","kind":"identifier"},{"kind":"text","text":" : "},{"text":"AdTagProperties","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)AdTagProperties","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdTagProperties","kind":"typeIdentifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd~1adResponseData\/title","value":"adResponseData","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd~1adResponseData\/fragments","value":[{"text":"adResponseData","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd~1isReadyToPlayAd\/title","value":"isReadyToPlayAd"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd~1isReadyToPlayAd\/fragments","value":[{"text":"isReadyToPlayAd","kind":"identifier"}]},{"value":"playAdWithVideoAdPlayerDelegate:adContainer:","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd~1playAd(videoAdPlayerDelegate:adContainer:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd~1playAd(videoAdPlayerDelegate:adContainer:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"playAdWithVideoAdPlayerDelegate:adContainer:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdTagProperties\/title","value":"AdTagProperties"},{"value":[{"kind":"identifier","text":"AdTagProperties"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdTagProperties\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd~1reset()\/title","value":"reset"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd~1reset()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reset"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd\/title","value":"VideoAd"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd\/fragments","value":[{"kind":"identifier","text":"VideoAd"}]},{"value":"loadAdWithLoadDelegate:","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd~1loadAd(loadDelegate:)\/title"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd~1loadAd(loadDelegate:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"loadAdWithLoadDelegate:","kind":"identifier"}]}]}]}