{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/videoadloaddelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/msadsdkvideo\/videoadloaddelegate"]}],"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"text":"VideoAdLoadDelegate protocol defines methods that an object can implement to receive notifications and handle events related to video ad loading and requests. This protocol is typically used to establish a delegate relationship between an ad loading component and another object (such as a view controller) that wants to monitor and respond to ad request outcomes.","type":"text"}],"sections":[],"metadata":{"modules":[{"name":"MSAdSDKVideo"}],"title":"VideoAdLoadDelegate","externalID":"c:@M@MSAdSDKVideo@objc(pl)VideoAdLoadDelegate","navigatorTitle":[{"text":"VideoAdLoadDelegate","kind":"identifier"}],"symbolKind":"protocol","role":"symbol","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoAdLoadDelegate"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdLoadDelegate"},"topicSections":[{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdLoadDelegate\/adLoadFailed(_:response:)","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdLoadDelegate\/adLoadSuccess(_:)"],"title":"Instance Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"VideoAdLoadDelegate","kind":"identifier"}]}]}],"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdLoadDelegate/adLoadSuccess(_:)":{"kind":"symbol","url":"\/documentation\/msadsdkvideo\/videoadloaddelegate\/adloadsuccess(_:)","type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"adLoadSuccess","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)AdResponseData","text":"AdResponseData"},{"kind":"text","text":")"}],"title":"adLoadSuccess(_:)","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdLoadDelegate\/adLoadSuccess(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"adLoadSuccess:"}],"role":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdLoadDelegate/adLoadFailed(_:response:)":{"navigatorTitle":[{"text":"adLoadFailed:response:","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/videoadloaddelegate\/adloadfailed(_:response:)","abstract":[],"title":"adLoadFailed(_:response:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"adLoadFailed","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":", ","kind":"text"},{"text":"response","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)AdResponseData","kind":"typeIdentifier","text":"AdResponseData"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdLoadDelegate\/adLoadFailed(_:response:)","kind":"symbol","required":true,"type":"topic","role":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdLoadDelegate":{"navigatorTitle":[{"kind":"identifier","text":"VideoAdLoadDelegate"}],"type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoAdLoadDelegate","kind":"identifier"}],"role":"symbol","abstract":[{"text":"VideoAdLoadDelegate protocol defines methods that an object can implement to receive notifications and handle events related to video ad loading and requests. This protocol is typically used to establish a delegate relationship between an ad loading component and another object (such as a view controller) that wants to monitor and respond to ad request outcomes.","type":"text"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdLoadDelegate","title":"VideoAdLoadDelegate","url":"\/documentation\/msadsdkvideo\/videoadloaddelegate"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"VideoAdLoadDelegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"value":[{"kind":"identifier","text":"VideoAdLoadDelegate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"VideoAdLoadDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdLoadDelegate\/adLoadFailed(_:response:)","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdLoadDelegate\/adLoadSuccess(_:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoAdLoadDelegate"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdLoadDelegate~1adLoadSuccess(_:)\/title","value":"adLoadSuccess:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"adLoadSuccess:"}],"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdLoadDelegate~1adLoadSuccess(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdLoadDelegate~1adLoadFailed(_:response:)\/title","op":"replace","value":"adLoadFailed:response:"},{"value":[{"text":"- ","kind":"text"},{"text":"adLoadFailed:response:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdLoadDelegate~1adLoadFailed(_:response:)\/fragments"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdLoadDelegate\/title","value":"VideoAdLoadDelegate","op":"replace"},{"value":[{"text":"VideoAdLoadDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdLoadDelegate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}