{"metadata":{"modules":[{"name":"MSAdSDKVideo"}],"symbolKind":"protocol","role":"symbol","externalID":"c:@M@MSAdSDKVideo@objc(pl)VideoAdPlayDelegate","navigatorTitle":[{"kind":"identifier","text":"VideoAdPlayDelegate"}],"title":"VideoAdPlayDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoAdPlayDelegate"}],"roleHeading":"Protocol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoAdPlayDelegate","kind":"identifier"}]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdPlayDelegate\/adPlaybackEvent(_:adEventData:)"]}],"abstract":[{"text":"VideoAdPlayDelegate protocol defines methods that an object can implement to receive and handle video ad playback events. This protocol is typically used to establish a delegate relationship between an ad playback component and another object (such as a view controller) that wants to monitor and respond to events during video ad playback.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/videoadplaydelegate"]},{"paths":["\/documentation\/msadsdkvideo\/videoadplaydelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdPlayDelegate"},"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdPlayDelegate":{"title":"VideoAdPlayDelegate","abstract":[{"text":"VideoAdPlayDelegate protocol defines methods that an object can implement to receive and handle video ad playback events. This protocol is typically used to establish a delegate relationship between an ad playback component and another object (such as a view controller) that wants to monitor and respond to events during video ad playback.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"VideoAdPlayDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoAdPlayDelegate"}],"url":"\/documentation\/msadsdkvideo\/videoadplaydelegate","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdPlayDelegate","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdPlayDelegate/adPlaybackEvent(_:adEventData:)":{"url":"\/documentation\/msadsdkvideo\/videoadplaydelegate\/adplaybackevent(_:adeventdata:)","required":true,"role":"symbol","navigatorTitle":[{"text":"adPlaybackEvent:adEventData:","kind":"identifier"}],"title":"adPlaybackEvent(_:adEventData:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdPlayDelegate\/adPlaybackEvent(_:adEventData:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adPlaybackEvent","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@MSAdSDKVideo@E@VideoAdEvent","text":"VideoAdEvent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"adEventData","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)AdEventData","text":"AdEventData","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"text":"This method is called when a video ad playback event occurs. It provides information about the specific event as well as associated ad data.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"playbackEvent: A VideoAdEvent enum case representing the event that occurred during video ad playback. Publishers can switch on this event to handle specific cases."},{"text":" ","type":"text"},{"type":"text","text":"adEventData: An instance of the AdEventData class containing additional data related to the ad event, such as ad duration, index, and error information."}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"value":"VideoAdPlayDelegate","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"VideoAdPlayDelegate"}],"op":"replace"},{"value":[{"text":"VideoAdPlayDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdPlayDelegate\/adPlaybackEvent(_:adEventData:)"]}]},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoAdPlayDelegate","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"VideoAdPlayDelegate","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdPlayDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdPlayDelegate\/fragments","value":[{"text":"VideoAdPlayDelegate","kind":"identifier"}]},{"op":"replace","value":"adPlaybackEvent:adEventData:","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdPlayDelegate~1adPlaybackEvent(_:adEventData:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdPlayDelegate~1adPlaybackEvent(_:adEventData:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adPlaybackEvent:adEventData:"}]}]}]}