{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"openDeviceBrowser"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/msadsdkvideo\/clickaction\/opendevicebrowser"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/msadsdkvideo\/clickaction\/opendevicebrowser"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction\/openDeviceBrowser"},"abstract":[{"text":"“openDeviceBrowser” function is responsible for triggering the device’s native web browser when a user interacts with  ad. In this scenario, the user is redirected to web browser, causing them to exit the app.","type":"text"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction"]]},"metadata":{"title":"ClickAction.openDeviceBrowser","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ClickActionOpenDeviceBrowser"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openDeviceBrowser","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"MSAdSDKVideo"}],"externalID":"c:@M@MSAdSDKVideo@E@ClickAction@ClickActionOpenDeviceBrowser","symbolKind":"case"},"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ClickAction/openDeviceBrowser":{"title":"ClickAction.openDeviceBrowser","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ClickActionOpenDeviceBrowser"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"openDeviceBrowser"}],"url":"\/documentation\/msadsdkvideo\/clickaction\/opendevicebrowser","kind":"symbol","type":"topic","abstract":[{"text":"“openDeviceBrowser” function is responsible for triggering the device’s native web browser when a user interacts with  ad. In this scenario, the user is redirected to web browser, causing them to exit the app.","type":"text"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction\/openDeviceBrowser"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ClickAction":{"title":"ClickAction","abstract":[{"text":"ClickAction’s responsibility is to overseeing and responding to user interactions with Ad.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"ClickAction","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClickAction"}],"url":"\/documentation\/msadsdkvideo\/clickaction","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"ClickActionOpenDeviceBrowser","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ClickActionOpenDeviceBrowser"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"ClickActionOpenDeviceBrowser","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ClickAction~1openDeviceBrowser\/title","value":"ClickActionOpenDeviceBrowser"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ClickAction~1openDeviceBrowser\/fragments","op":"replace","value":[{"text":"ClickActionOpenDeviceBrowser","kind":"identifier"}]},{"op":"replace","value":"ClickAction","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ClickAction\/title"},{"value":[{"text":"ClickAction","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ClickAction\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}