{"identifier":{"url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction\/openSDKBrowser","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"“openSDKBrowser” function is designed to launch an in-app browser within the SDK when a user interacts with an ad"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"openSDKBrowser"}]}]}],"variants":[{"paths":["\/documentation\/msadsdkvideo\/clickaction\/opensdkbrowser"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/msadsdkvideo\/clickaction\/opensdkbrowser"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ClickActionOpenSDKBrowser"}],"title":"ClickAction.openSDKBrowser","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"openSDKBrowser"}],"roleHeading":"Case","role":"symbol","symbolKind":"case","modules":[{"name":"MSAdSDKVideo"}],"externalID":"c:@M@MSAdSDKVideo@E@ClickAction@ClickActionOpenSDKBrowser"},"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ClickAction":{"title":"ClickAction","abstract":[{"text":"ClickAction’s responsibility is to overseeing and responding to user interactions with Ad.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"ClickAction","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClickAction"}],"url":"\/documentation\/msadsdkvideo\/clickaction","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ClickAction/openSDKBrowser":{"navigatorTitle":[{"kind":"identifier","text":"ClickActionOpenSDKBrowser"}],"url":"\/documentation\/msadsdkvideo\/clickaction\/opensdkbrowser","abstract":[{"type":"text","text":"“openSDKBrowser” function is designed to launch an in-app browser within the SDK when a user interacts with an ad"}],"title":"ClickAction.openSDKBrowser","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"openSDKBrowser","kind":"identifier"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction\/openSDKBrowser","kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"ClickActionOpenSDKBrowser","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"ClickActionOpenSDKBrowser","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ClickActionOpenSDKBrowser"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ClickAction","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ClickAction\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ClickAction\/fragments","value":[{"kind":"identifier","text":"ClickAction"}]},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ClickAction~1openSDKBrowser\/title","op":"replace","value":"ClickActionOpenSDKBrowser"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ClickAction~1openSDKBrowser\/fragments","value":[{"text":"ClickActionOpenSDKBrowser","kind":"identifier"}]}]}]}