{"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"adWillLeaveApplication","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/videoadevent\/adwillleaveapplication"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/msadsdkvideo\/videoadevent\/adwillleaveapplication"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/adWillLeaveApplication"},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adWillLeaveApplication"}],"roleHeading":"Case","symbolKind":"case","title":"VideoAdEvent.adWillLeaveApplication","navigatorTitle":[{"kind":"identifier","text":"VideoAdEventAdWillLeaveApplication"}],"modules":[{"name":"MSAdSDKVideo"}],"role":"symbol","externalID":"c:@M@MSAdSDKVideo@E@VideoAdEvent@VideoAdEventAdWillLeaveApplication"},"abstract":[{"type":"text","text":"Indicates that the ad will leave the application, typically when clicking on the ad."}],"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent/adWillLeaveApplication":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/adWillLeaveApplication","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adWillLeaveApplication"}],"type":"topic","title":"VideoAdEvent.adWillLeaveApplication","abstract":[{"text":"Indicates that the ad will leave the application, typically when clicking on the ad.","type":"text"}],"navigatorTitle":[{"text":"VideoAdEventAdWillLeaveApplication","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/videoadevent\/adwillleaveapplication"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent":{"abstract":[],"title":"VideoAdEvent","role":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent","url":"\/documentation\/msadsdkvideo\/videoadevent","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoAdEvent","kind":"identifier"}],"navigatorTitle":[{"text":"VideoAdEvent","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"VideoAdEventAdWillLeaveApplication","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"VideoAdEventAdWillLeaveApplication"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"VideoAdEventAdWillLeaveApplication"}]}]}},{"value":"VideoAdEventAdWillLeaveApplication","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1adWillLeaveApplication\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1adWillLeaveApplication\/fragments","value":[{"kind":"identifier","text":"VideoAdEventAdWillLeaveApplication"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent\/title","value":"VideoAdEvent"},{"value":[{"text":"VideoAdEvent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}