{"identifier":{"url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/fourthQuartile","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fourthQuartile"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"Marks the event when the video ad has reached the fourth quartile of playback.","type":"text"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"VideoAdEventFourthQuartile"}],"externalID":"c:@M@MSAdSDKVideo@E@VideoAdEvent@VideoAdEventFourthQuartile","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fourthQuartile"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","modules":[{"name":"MSAdSDKVideo"}],"title":"VideoAdEvent.fourthQuartile"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/videoadevent\/fourthquartile"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/msadsdkvideo\/videoadevent\/fourthquartile"]}],"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent"]]},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent/fourthQuartile":{"title":"VideoAdEvent.fourthQuartile","role":"symbol","navigatorTitle":[{"text":"VideoAdEventFourthQuartile","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fourthQuartile"}],"url":"\/documentation\/msadsdkvideo\/videoadevent\/fourthquartile","kind":"symbol","abstract":[{"type":"text","text":"Marks the event when the video ad has reached the fourth quartile of playback."}],"type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/fourthQuartile"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent":{"abstract":[],"title":"VideoAdEvent","role":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent","url":"\/documentation\/msadsdkvideo\/videoadevent","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoAdEvent","kind":"identifier"}],"navigatorTitle":[{"text":"VideoAdEvent","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"VideoAdEventFourthQuartile"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"VideoAdEventFourthQuartile","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"VideoAdEventFourthQuartile"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"VideoAdEventFourthQuartile","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1fourthQuartile\/title"},{"op":"replace","value":[{"text":"VideoAdEventFourthQuartile","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1fourthQuartile\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent\/title","value":"VideoAdEvent"},{"op":"replace","value":[{"kind":"identifier","text":"VideoAdEvent"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}