{"metadata":{"role":"symbol","title":"VideoAdEvent.midQuartile","externalID":"c:@M@MSAdSDKVideo@E@VideoAdEvent@VideoAdEventMidQuartile","navigatorTitle":[{"kind":"identifier","text":"VideoAdEventMidQuartile"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"midQuartile","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"MSAdSDKVideo"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/midQuartile","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"midQuartile","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"abstract":[{"text":"Marks the event when the video ad has reached the mid-quartile of playback.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/videoadevent\/midquartile"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/msadsdkvideo\/videoadevent\/midquartile"]}],"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent"]]},"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent/midQuartile":{"title":"VideoAdEvent.midQuartile","role":"symbol","navigatorTitle":[{"text":"VideoAdEventMidQuartile","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"midQuartile","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/videoadevent\/midquartile","kind":"symbol","type":"topic","abstract":[{"text":"Marks the event when the video ad has reached the mid-quartile of playback.","type":"text"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/midQuartile"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent":{"abstract":[],"title":"VideoAdEvent","role":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent","url":"\/documentation\/msadsdkvideo\/videoadevent","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoAdEvent","kind":"identifier"}],"navigatorTitle":[{"text":"VideoAdEvent","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"VideoAdEventMidQuartile"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"VideoAdEventMidQuartile","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"VideoAdEventMidQuartile","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"VideoAdEventMidQuartile","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1midQuartile\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1midQuartile\/fragments","value":[{"text":"VideoAdEventMidQuartile","kind":"identifier"}]},{"value":"VideoAdEvent","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent\/fragments","value":[{"kind":"identifier","text":"VideoAdEvent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}