{"metadata":{"role":"symbol","modules":[{"name":"MSAdSDKVideo"}],"symbolKind":"case","navigatorTitle":[{"text":"VideoAdEventMuteOff","kind":"identifier"}],"title":"VideoAdEvent.muteOff","externalID":"c:@M@MSAdSDKVideo@E@VideoAdEvent@VideoAdEventMuteOff","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"muteOff","kind":"identifier"}]},"abstract":[{"text":"Signifies that the mute setting for the video ad has been turned off.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/muteOff"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"muteOff","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent"]]},"variants":[{"paths":["\/documentation\/msadsdkvideo\/videoadevent\/muteoff"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/msadsdkvideo\/videoadevent\/muteoff"]}],"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent":{"abstract":[],"title":"VideoAdEvent","role":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent","url":"\/documentation\/msadsdkvideo\/videoadevent","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoAdEvent","kind":"identifier"}],"navigatorTitle":[{"text":"VideoAdEvent","kind":"identifier"}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent/muteOff":{"title":"VideoAdEvent.muteOff","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"muteOff","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"VideoAdEventMuteOff"}],"url":"\/documentation\/msadsdkvideo\/videoadevent\/muteoff","kind":"symbol","abstract":[{"type":"text","text":"Signifies that the mute setting for the video ad has been turned off."}],"type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/muteOff"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"VideoAdEventMuteOff","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"VideoAdEventMuteOff","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"VideoAdEventMuteOff","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent\/title","value":"VideoAdEvent","op":"replace"},{"value":[{"kind":"identifier","text":"VideoAdEvent"}],"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1muteOff\/title","value":"VideoAdEventMuteOff"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1muteOff\/fragments","value":[{"text":"VideoAdEventMuteOff","kind":"identifier"}]}]}]}