{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/returnURL"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent"]]},"abstract":[{"type":"text","text":"Represents the case when a URL is returned as part of ad interaction. This URL is assumed to be handled by the caller."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnURL"}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/videoadevent\/returnurl"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/msadsdkvideo\/videoadevent\/returnurl"]}],"metadata":{"navigatorTitle":[{"text":"VideoAdEventReturnURL","kind":"identifier"}],"role":"symbol","title":"VideoAdEvent.returnURL","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"returnURL","kind":"identifier"}],"modules":[{"name":"MSAdSDKVideo"}],"roleHeading":"Case","externalID":"c:@M@MSAdSDKVideo@E@VideoAdEvent@VideoAdEventReturnURL"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent":{"abstract":[],"title":"VideoAdEvent","role":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent","url":"\/documentation\/msadsdkvideo\/videoadevent","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoAdEvent","kind":"identifier"}],"navigatorTitle":[{"text":"VideoAdEvent","kind":"identifier"}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent/returnURL":{"title":"VideoAdEvent.returnURL","role":"symbol","navigatorTitle":[{"text":"VideoAdEventReturnURL","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"returnURL","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/videoadevent\/returnurl","kind":"symbol","abstract":[{"type":"text","text":"Represents the case when a URL is returned as part of ad interaction. This URL is assumed to be handled by the caller."}],"type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent\/returnURL"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"VideoAdEventReturnURL"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"VideoAdEventReturnURL"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"VideoAdEventReturnURL"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"VideoAdEvent","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent\/fragments","value":[{"text":"VideoAdEvent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1returnURL\/title","value":"VideoAdEventReturnURL"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent~1returnURL\/fragments","value":[{"text":"VideoAdEventReturnURL","kind":"identifier"}]}]}]}