{"kind":"symbol","metadata":{"externalID":"c:@M@MSAdSDKVideo@objc(cs)AdEventData(py)activeAdIndex","modules":[{"name":"MSAdSDKVideo"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","title":"activeAdIndex","navigatorTitle":[{"kind":"identifier","text":"activeAdIndex"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activeAdIndex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"abstract":[{"type":"text","text":"Indicates the index position of the ad that is currently being displayed within a sequence of ads. This property helps track the ad’s position within a playlist or sequence."},{"text":" ","type":"text"},{"type":"text","text":"Default Value: -1 which means no ad loaded"}],"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData"]]},"identifier":{"url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData\/activeAdIndex","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activeAdIndex","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/adeventdata\/activeadindex"]},{"paths":["\/documentation\/msadsdkvideo\/adeventdata\/activeadindex"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/AdEventData":{"role":"symbol","title":"AdEventData","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData","kind":"symbol","abstract":[{"text":"AdEventData class is designed to encapsulate essential information related to ad events and ad playback. It serves as a data structure to store data about the currently displayed ad, including its duration, position within a sequence, total ad count, click URL upon ad interaction, and any potential error that may occur during ad playback.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdEventData"}],"navigatorTitle":[{"text":"AdEventData","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/adeventdata"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/AdEventData/activeAdIndex":{"kind":"symbol","title":"activeAdIndex","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"activeAdIndex","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","navigatorTitle":[{"text":"activeAdIndex","kind":"identifier"}],"type":"topic","abstract":[{"text":"Indicates the index position of the ad that is currently being displayed within a sequence of ads. This property helps track the ad’s position within a playlist or sequence.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default Value: -1 which means no ad loaded"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData\/activeAdIndex","url":"\/documentation\/msadsdkvideo\/adeventdata\/activeadindex"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"activeAdIndex"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"activeAdIndex"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"text":"activeAdIndex","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"AdEventData","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdEventData\/title","op":"replace"},{"value":[{"text":"AdEventData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdEventData\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdEventData~1activeAdIndex\/title","value":"activeAdIndex","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdEventData~1activeAdIndex\/fragments","value":[{"text":"activeAdIndex","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}