{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clickURL"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData\/clickURL"},"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData"]]},"metadata":{"role":"symbol","title":"clickURL","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clickURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"symbolKind":"property","navigatorTitle":[{"text":"clickURL","kind":"identifier"}],"externalID":"c:@M@MSAdSDKVideo@objc(cs)AdEventData(py)clickURL","modules":[{"name":"MSAdSDKVideo"}],"roleHeading":"Instance Property"},"sections":[],"abstract":[{"type":"text","text":"Holds the click URL returned when the user interacts with the ad. This URL typically points to a destination or action triggered upon ad click. It is an optional property that may be nil if no click URL is available."},{"type":"text","text":" "},{"text":"Default Value: nil","type":"text"},{"type":"text","text":" "},{"text":"Property type: Optional","type":"text"}],"variants":[{"paths":["\/documentation\/msadsdkvideo\/adeventdata\/clickurl"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/msadsdkvideo\/adeventdata\/clickurl"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/AdEventData":{"role":"symbol","title":"AdEventData","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData","kind":"symbol","abstract":[{"text":"AdEventData class is designed to encapsulate essential information related to ad events and ad playback. It serves as a data structure to store data about the currently displayed ad, including its duration, position within a sequence, total ad count, click URL upon ad interaction, and any potential error that may occur during ad playback.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdEventData"}],"navigatorTitle":[{"text":"AdEventData","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/adeventdata"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/AdEventData/clickURL":{"kind":"symbol","title":"clickURL","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clickURL"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"text":"clickURL","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Holds the click URL returned when the user interacts with the ad. This URL typically points to a destination or action triggered upon ad click. It is an optional property that may be nil if no click URL is available."},{"type":"text","text":" "},{"type":"text","text":"Default Value: nil"},{"type":"text","text":" "},{"text":"Property type: Optional","type":"text"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData\/clickURL","url":"\/documentation\/msadsdkvideo\/adeventdata\/clickurl"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"clickURL"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"clickURL"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"clickURL"}],"languages":["occ"]}]},"op":"replace"},{"value":"AdEventData","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdEventData\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdEventData\/fragments","value":[{"text":"AdEventData","kind":"identifier"}]},{"value":"clickURL","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdEventData~1clickURL\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdEventData~1clickURL\/fragments","op":"replace","value":[{"kind":"identifier","text":"clickURL"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}