{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"preCacheObjects"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"memberId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": ((","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"preCacheObjects (Bool)","content":[{"inlineContent":[{"text":"A boolean value that determines whether preCacheObjects should be enabled for preloading the User Agent, webview etc. When set to true, it indicates that preloading of User Agent is enabled. When set to false, preloading is disabled.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Add member id for publisher"}],"type":"paragraph"}],"name":"memberId (Int)"},{"name":"completionHandler ((Bool) -> Void)?","content":[{"inlineContent":[{"type":"text","text":"An optional completion handler closure that is called once the initialization process is complete. The closure takes one parameter, a boolean value (Bool), which indicates the status of the initialization process. A value of true typically signifies successful initialization, while false indicates an unsuccessful initialization"}],"type":"paragraph"}]}]}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"initialize(preCacheObjects:memberId:completionHandler:)","modules":[{"name":"MSAdSDKVideo"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preCacheObjects","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"memberId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"text":"initializeWithPreCacheObjects:memberId:completionHandler:","kind":"identifier"}],"externalID":"c:@M@MSAdSDKVideo@objc(cs)MSAdSDKInstream(im)initializeWithPreCacheObjects:memberId:completionHandler:","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSAdSDKInstream"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/msadsdkinstream\/initialize(precacheobjects:memberid:completionhandler:)"]},{"paths":["\/documentation\/msadsdkvideo\/msadsdkinstream\/initialize(precacheobjects:memberid:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Initiates will allow to enable preCacheObjects to perform preloading of User Agent","type":"text"}],"identifier":{"url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSAdSDKInstream\/initialize(preCacheObjects:memberId:completionHandler:)","interfaceLanguage":"swift"},"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSAdSDKInstream":{"title":"MSAdSDKInstream","abstract":[{"text":"MSAdSDKVideo  ensures that the sdk loads up with the required configuration like userAgent Network Manager","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"MSAdSDKInstream","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MSAdSDKInstream"}],"url":"\/documentation\/msadsdkvideo\/msadsdkinstream","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSAdSDKInstream","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSAdSDKInstream/initialize(preCacheObjects:memberId:completionHandler:)":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSAdSDKInstream\/initialize(preCacheObjects:memberId:completionHandler:)","url":"\/documentation\/msadsdkvideo\/msadsdkinstream\/initialize(precacheobjects:memberid:completionhandler:)","title":"initialize(preCacheObjects:memberId:completionHandler:)","abstract":[{"text":"Initiates will allow to enable preCacheObjects to perform preloading of User Agent","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preCacheObjects","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"memberId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"initializeWithPreCacheObjects:memberId:completionHandler:","kind":"identifier"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"initializeWithPreCacheObjects:memberId:completionHandler:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initializeWithPreCacheObjects:memberId:completionHandler:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"initializeWithPreCacheObjects:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"preCacheObjects","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"memberId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"memberId"},{"kind":"text","text":" "},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#b)","text":"void (^)(_Bool)","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1MSAdSDKInstream\/title","op":"replace","value":"MSAdSDKInstream"},{"value":[{"text":"MSAdSDKInstream","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1MSAdSDKInstream\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1MSAdSDKInstream~1initialize(preCacheObjects:memberId:completionHandler:)\/title","value":"initializeWithPreCacheObjects:memberId:completionHandler:"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1MSAdSDKInstream~1initialize(preCacheObjects:memberId:completionHandler:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initializeWithPreCacheObjects:memberId:completionHandler:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}