{"sections":[],"metadata":{"symbolKind":"method","roleHeading":"Type Method","externalID":"c:@M@MSAdSDKVideo@objc(cs)MSAdSDKInstream(cm)sharedInstance","modules":[{"name":"MSAdSDKVideo"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sharedInstance","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"MSAdSDKInstream","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)MSAdSDKInstream","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"sharedInstance","kind":"identifier"}],"title":"sharedInstance()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sharedInstance","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MSAdSDKInstream","kind":"typeIdentifier","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSAdSDKInstream","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)MSAdSDKInstream"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/msadsdkvideo\/msadsdkinstream\/sharedinstance()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/msadsdkvideo\/msadsdkinstream\/sharedinstance()"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"sharedInstance method is a static class function that provides access to a shared instance of the MSAdSDKVideo class. the Singleton design pattern, ensuring that there is only one instance of MSAdSDKVideo created and reused across your application’s lifecycle.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSAdSDKInstream\/sharedInstance()"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSAdSDKInstream"]]},"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSAdSDKInstream/sharedInstance()":{"url":"\/documentation\/msadsdkvideo\/msadsdkinstream\/sharedinstance()","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSAdSDKInstream\/sharedInstance()","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sharedInstance","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MSAdSDKInstream","kind":"typeIdentifier","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)MSAdSDKInstream"}],"type":"topic","abstract":[{"type":"text","text":"sharedInstance method is a static class function that provides access to a shared instance of the MSAdSDKVideo class. the Singleton design pattern, ensuring that there is only one instance of MSAdSDKVideo created and reused across your application’s lifecycle."}],"role":"symbol","navigatorTitle":[{"text":"sharedInstance","kind":"identifier"}],"kind":"symbol","title":"sharedInstance()"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSAdSDKInstream":{"title":"MSAdSDKInstream","abstract":[{"text":"MSAdSDKVideo  ensures that the sdk loads up with the required configuration like userAgent Network Manager","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"MSAdSDKInstream","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MSAdSDKInstream"}],"url":"\/documentation\/msadsdkvideo\/msadsdkinstream","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSAdSDKInstream","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"sharedInstance","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sharedInstance"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)MSAdSDKInstream","kind":"typeIdentifier","text":"MSAdSDKInstream","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSAdSDKInstream"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"sharedInstance"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"sharedInstance","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1MSAdSDKInstream~1sharedInstance()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1MSAdSDKInstream~1sharedInstance()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sharedInstance","kind":"identifier"}]},{"op":"replace","value":"MSAdSDKInstream","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1MSAdSDKInstream\/title"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1MSAdSDKInstream\/fragments","value":[{"kind":"identifier","text":"MSAdSDKInstream"}],"op":"replace"}]}]}