{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/debug"},"metadata":{"externalID":"c:@M@MSAdSDKVideo@E@LogLevel@LogLevelDebug","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debug"}],"modules":[{"name":"MSAdSDKVideo"}],"title":"LogLevel.debug","navigatorTitle":[{"kind":"identifier","text":"LogLevelDebug"}],"roleHeading":"Case","symbolKind":"case","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debug"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/msadsdkvideo\/loglevel\/debug"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/msadsdkvideo\/loglevel\/debug"]}],"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/LogLevel/debug":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debug"}],"kind":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/debug","url":"\/documentation\/msadsdkvideo\/loglevel\/debug","abstract":[],"title":"LogLevel.debug","navigatorTitle":[{"text":"LogLevelDebug","kind":"identifier"}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/LogLevel":{"title":"LogLevel","abstract":[{"text":"LogLevel defines different log levels, each with an associated integer value for fine-tuned control over log verbosity.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"LogLevel","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"url":"\/documentation\/msadsdkvideo\/loglevel","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"LogLevelDebug"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"LogLevelDebug","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"LogLevelDebug","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel~1debug\/title","value":"LogLevelDebug"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel~1debug\/fragments","value":[{"text":"LogLevelDebug","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel\/title","op":"replace","value":"LogLevel"},{"value":[{"text":"LogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel\/fragments","op":"replace"}]}]}