{"identifier":{"url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/info","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel"]]},"metadata":{"role":"symbol","modules":[{"name":"MSAdSDKVideo"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"LogLevelInfo"}],"title":"LogLevel.info","externalID":"c:@M@MSAdSDKVideo@E@LogLevel@LogLevelInfo","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"info","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/msadsdkvideo\/loglevel\/info"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/msadsdkvideo\/loglevel\/info"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"info","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/LogLevel":{"title":"LogLevel","abstract":[{"text":"LogLevel defines different log levels, each with an associated integer value for fine-tuned control over log verbosity.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"LogLevel","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"url":"\/documentation\/msadsdkvideo\/loglevel","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/LogLevel/info":{"role":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/info","navigatorTitle":[{"text":"LogLevelInfo","kind":"identifier"}],"type":"topic","title":"LogLevel.info","url":"\/documentation\/msadsdkvideo\/loglevel\/info","abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"info","kind":"identifier"}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"LogLevelInfo","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"LogLevelInfo","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"LogLevelInfo","kind":"identifier"}]}],"kind":"declarations"}},{"value":"LogLevel","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel\/fragments","op":"replace","value":[{"text":"LogLevel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel~1info\/title","value":"LogLevelInfo","op":"replace"},{"value":[{"text":"LogLevelInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel~1info\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}