{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"trace"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"roleHeading":"Case","role":"symbol","modules":[{"name":"MSAdSDKVideo"}],"title":"LogLevel.trace","externalID":"c:@M@MSAdSDKVideo@E@LogLevel@LogLevelTrace","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trace","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"text":"LogLevelTrace","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/loglevel\/trace"]},{"paths":["\/documentation\/msadsdkvideo\/loglevel\/trace"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/trace","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel"]]},"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/LogLevel/trace":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trace"}],"title":"LogLevel.trace","navigatorTitle":[{"kind":"identifier","text":"LogLevelTrace"}],"url":"\/documentation\/msadsdkvideo\/loglevel\/trace","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel\/trace","abstract":[],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/LogLevel":{"title":"LogLevel","abstract":[{"text":"LogLevel defines different log levels, each with an associated integer value for fine-tuned control over log verbosity.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"LogLevel","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"url":"\/documentation\/msadsdkvideo\/loglevel","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"LogLevelTrace","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"LogLevelTrace","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"LogLevelTrace"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel~1trace\/title","value":"LogLevelTrace"},{"value":[{"text":"LogLevelTrace","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel~1trace\/fragments"},{"value":"LogLevel","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel\/fragments","op":"replace","value":[{"text":"LogLevel","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}