{"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdLoadDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdLoadDelegate\/adLoadSuccess(_:)"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"adLoadSuccess","kind":"identifier"},{"kind":"text","text":"("},{"text":"AdResponseData","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)AdResponseData","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","externalID":"c:@M@MSAdSDKVideo@objc(pl)VideoAdLoadDelegate(im)adLoadSuccess:","title":"adLoadSuccess(_:)","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"adLoadSuccess:","kind":"identifier"}],"modules":[{"name":"MSAdSDKVideo"}],"required":true},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/videoadloaddelegate\/adloadsuccess(_:)"]},{"paths":["\/documentation\/msadsdkvideo\/videoadloaddelegate\/adloadsuccess(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"adLoadSuccess","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"response"},{"text":": ","kind":"text"},{"text":"AdResponseData","kind":"typeIdentifier","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdResponseData","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)AdResponseData"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/AdResponseData":{"title":"AdResponseData","kind":"symbol","url":"\/documentation\/msadsdkvideo\/adresponsedata","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdResponseData"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"AdResponseData","kind":"identifier"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdResponseData","abstract":[{"type":"text","text":"AdResponseData class is designed to encapsulate data related to ad responses, particularly for fetching ad content from a URL. This class provides properties for storing the URL of the ad content and any potential errors that may occur during the ad request and retrieval process."}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","type":"topic","url":"\/documentation\/msadsdkvideo","role":"collection","title":"MSAdSDKVideo"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdLoadDelegate":{"navigatorTitle":[{"kind":"identifier","text":"VideoAdLoadDelegate"}],"type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoAdLoadDelegate","kind":"identifier"}],"role":"symbol","abstract":[{"text":"VideoAdLoadDelegate protocol defines methods that an object can implement to receive notifications and handle events related to video ad loading and requests. This protocol is typically used to establish a delegate relationship between an ad loading component and another object (such as a view controller) that wants to monitor and respond to ad request outcomes.","type":"text"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdLoadDelegate","title":"VideoAdLoadDelegate","url":"\/documentation\/msadsdkvideo\/videoadloaddelegate"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdLoadDelegate/adLoadSuccess(_:)":{"kind":"symbol","url":"\/documentation\/msadsdkvideo\/videoadloaddelegate\/adloadsuccess(_:)","type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"adLoadSuccess","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)AdResponseData","text":"AdResponseData"},{"kind":"text","text":")"}],"title":"adLoadSuccess(_:)","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdLoadDelegate\/adLoadSuccess(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"adLoadSuccess:"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"adLoadSuccess:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"adLoadSuccess:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"adLoadSuccess:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdResponseData","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)AdResponseData","text":"AdResponseData"},{"text":" *) ","kind":"text"},{"text":"response","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdResponseData\/title","value":"AdResponseData","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdResponseData\/fragments","value":[{"text":"AdResponseData","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdLoadDelegate\/title","value":"VideoAdLoadDelegate"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdLoadDelegate\/fragments","value":[{"text":"VideoAdLoadDelegate","kind":"identifier"}],"op":"replace"},{"value":"adLoadSuccess:","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdLoadDelegate~1adLoadSuccess(_:)\/title"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdLoadDelegate~1adLoadSuccess(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"adLoadSuccess:"}],"op":"replace"}]}]}