{"metadata":{"navigatorTitle":[{"text":"adLoadFailed:response:","kind":"identifier"}],"title":"adLoadFailed(_:response:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"adLoadFailed","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"response"},{"kind":"text","text":": "},{"text":"AdResponseData","kind":"typeIdentifier","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)AdResponseData"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","role":"symbol","required":true,"modules":[{"name":"MSAdSDKVideo"}],"symbolKind":"method","externalID":"c:@M@MSAdSDKVideo@objc(pl)VideoAdLoadDelegate(im)adLoadFailed:response:"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/msadsdkvideo\/videoadloaddelegate\/adloadfailed(_:response:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/msadsdkvideo\/videoadloaddelegate\/adloadfailed(_:response:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"adLoadFailed","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":", ","kind":"text"},{"text":"response","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdResponseData","kind":"typeIdentifier","text":"AdResponseData","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)AdResponseData"},{"kind":"text","text":")"}]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdLoadDelegate\/adLoadFailed(_:response:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdLoadDelegate"]]},"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/AdResponseData":{"title":"AdResponseData","kind":"symbol","url":"\/documentation\/msadsdkvideo\/adresponsedata","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdResponseData"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"AdResponseData","kind":"identifier"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdResponseData","abstract":[{"type":"text","text":"AdResponseData class is designed to encapsulate data related to ad responses, particularly for fetching ad content from a URL. This class provides properties for storing the URL of the ad content and any potential errors that may occur during the ad request and retrieval process."}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdLoadDelegate/adLoadFailed(_:response:)":{"navigatorTitle":[{"text":"adLoadFailed:response:","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/videoadloaddelegate\/adloadfailed(_:response:)","abstract":[],"title":"adLoadFailed(_:response:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"adLoadFailed","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":", ","kind":"text"},{"text":"response","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)AdResponseData","kind":"typeIdentifier","text":"AdResponseData"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdLoadDelegate\/adLoadFailed(_:response:)","kind":"symbol","required":true,"type":"topic","role":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdLoadDelegate":{"navigatorTitle":[{"kind":"identifier","text":"VideoAdLoadDelegate"}],"type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoAdLoadDelegate","kind":"identifier"}],"role":"symbol","abstract":[{"text":"VideoAdLoadDelegate protocol defines methods that an object can implement to receive notifications and handle events related to video ad loading and requests. This protocol is typically used to establish a delegate relationship between an ad loading component and another object (such as a view controller) that wants to monitor and respond to ad request outcomes.","type":"text"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdLoadDelegate","title":"VideoAdLoadDelegate","url":"\/documentation\/msadsdkvideo\/videoadloaddelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"adLoadFailed:response:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adLoadFailed:response:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"adLoadFailed:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"response:","kind":"identifier"},{"kind":"text","text":"("},{"text":"AdResponseData","kind":"typeIdentifier","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdResponseData","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)AdResponseData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"response"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"AdResponseData","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdResponseData\/title"},{"op":"replace","value":[{"text":"AdResponseData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdResponseData\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdLoadDelegate~1adLoadFailed(_:response:)\/title","value":"adLoadFailed:response:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"adLoadFailed:response:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdLoadDelegate~1adLoadFailed(_:response:)\/fragments"},{"value":"VideoAdLoadDelegate","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdLoadDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdLoadDelegate\/fragments","op":"replace","value":[{"text":"VideoAdLoadDelegate","kind":"identifier"}]}]}]}