{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/adtagproperties\/setrequesturls(_:)"]},{"paths":["\/documentation\/msadsdkvideo\/adtagproperties\/setrequesturls(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdTagProperties\/setRequestURLs(_:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"setRequestURLs:"}],"externalID":"c:@M@MSAdSDKVideo@objc(cs)AdTagProperties(im)setRequestURLs:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setRequestURLs","kind":"identifier"},{"kind":"text","text":"(["},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"MSAdSDKVideo"}],"title":"setRequestURLs(_:)"},"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdTagProperties"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRequestURLs"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"urls"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"An array of URL objects that represent the URLs required for the video ad request. These URLs typically include  ad server endpoint for fetching ad creatives."}],"type":"paragraph"}],"name":"urls"}],"kind":"parameters"}],"abstract":[{"text":"setRequestURLs method is responsible for configuring a list of URLs that are essential for the video ad request. The method allows publisher to provide the  URLs that the http request  component will use during the ad request process. These URLs  include endpoints for fetching ad content like vastXML.","type":"text"}],"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/AdTagProperties/setRequestURLs(_:)":{"role":"symbol","type":"topic","abstract":[{"text":"setRequestURLs method is responsible for configuring a list of URLs that are essential for the video ad request. The method allows publisher to provide the  URLs that the http request  component will use during the ad request process. These URLs  include endpoints for fetching ad content like vastXML.","type":"text"}],"url":"\/documentation\/msadsdkvideo\/adtagproperties\/setrequesturls(_:)","title":"setRequestURLs(_:)","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdTagProperties\/setRequestURLs(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setRequestURLs","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"])"}],"navigatorTitle":[{"text":"setRequestURLs:","kind":"identifier"}],"kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/AdTagProperties":{"role":"symbol","title":"AdTagProperties","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdTagProperties","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdTagProperties"}],"navigatorTitle":[{"kind":"identifier","text":"AdTagProperties"}],"url":"\/documentation\/msadsdkvideo\/adtagproperties"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"setRequestURLs:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setRequestURLs:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setRequestURLs:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSURL *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"urls"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"setRequestURLs:","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdTagProperties~1setRequestURLs(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdTagProperties~1setRequestURLs(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setRequestURLs:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdTagProperties\/title","value":"AdTagProperties"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdTagProperties\/fragments","value":[{"kind":"identifier","text":"AdTagProperties"}]}]}]}