{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"browserDismissTitle","modules":[{"name":"MSAdSDKVideo"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"browserDismissTitle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"symbolKind":"property","navigatorTitle":[{"text":"browserDismissTitle","kind":"identifier"}],"externalID":"c:@M@MSAdSDKVideo@objc(cs)SDKSettings(py)browserDismissTitle","role":"symbol"},"abstract":[{"type":"text","text":"browserDismissTitle property is used to specify the title of the dismiss button for an in-app browser.The button allows users to close or dismiss the in-app browser when they have finished viewing its content. The property allows publishers to customize the text displayed on this dismiss button."},{"text":" ","type":"text"},{"type":"text","text":"Default Value: “OK”"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/sdksettings\/browserdismisstitle"]},{"paths":["\/documentation\/msadsdkvideo\/sdksettings\/browserdismisstitle"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/browserDismissTitle","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"browserDismissTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/SDKSettings":{"title":"SDKSettings","abstract":[{"text":"SDKSettings class is responsible for managing global settings for the SDK that are shared and common between multiple ad requests. It ensures consistency and ease of maintenance by allowing publishers to set these settings in one place, and the SDK uses these settings for all subsequent ad requests.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SDKSettings","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKSettings"}],"url":"\/documentation\/msadsdkvideo\/sdksettings","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/SDKSettings/browserDismissTitle":{"navigatorTitle":[{"kind":"identifier","text":"browserDismissTitle"}],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"browserDismissTitle"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/browserDismissTitle","abstract":[{"text":"browserDismissTitle property is used to specify the title of the dismiss button for an in-app browser.The button allows users to close or dismiss the in-app browser when they have finished viewing its content. The property allows publishers to customize the text displayed on this dismiss button.","type":"text"},{"text":" ","type":"text"},{"text":"Default Value: “OK”","type":"text"}],"title":"browserDismissTitle","url":"\/documentation\/msadsdkvideo\/sdksettings\/browserdismisstitle"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"browserDismissTitle"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"browserDismissTitle","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"browserDismissTitle","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings\/title","value":"SDKSettings"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings\/fragments","op":"replace","value":[{"text":"SDKSettings","kind":"identifier"}]},{"value":"browserDismissTitle","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings~1browserDismissTitle\/title"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings~1browserDismissTitle\/fragments","op":"replace","value":[{"text":"browserDismissTitle","kind":"identifier"}]}]}]}