{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"clickAction property allows publisher to define the behavior of the SDK when a user interacts with the ad. This property offers three distinct options, each of which defines how the SDK should handle the click-through URL associated with the ad."}],"identifier":{"url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/clickAction","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clickAction"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MSAdSDKVideo@E@ClickAction","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction","text":"ClickAction","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":".openDeviceBrowser: This option instructs the SDK to open the click-through URL in the external device browser. When selected, clicking on the ad will result in the user leaving the app to view the URL in their device’s default web browser."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":".openSDKBrowser: With this option, the SDK will open the click-through URL in its in-app browser. This means that when the user clicks on the ad, the URL will be displayed within the SDK’s built-in browser, allowing them to interact with the content without leaving the app."}]},{"inlineContent":[{"text":".returnURL: Choosing this option will result in the URL being returned to the calling environment without opening any browser. The SDK will provide the URL to the caller via the delegate PlayDelegate’s ’.returnURL VideoAdEvent. It is assumed that the caller will handle the URL appropriately, including displaying its content to the user within the app.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default Value: .openDeviceBrowser"}]}]}],"variants":[{"paths":["\/documentation\/msadsdkvideo\/sdksettings\/clickaction"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/msadsdkvideo\/sdksettings\/clickaction"]}],"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings"]]},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"clickAction","kind":"identifier"},{"kind":"text","text":": "},{"text":"ClickAction","kind":"typeIdentifier","preciseIdentifier":"c:@M@MSAdSDKVideo@E@ClickAction"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"clickAction"}],"title":"clickAction","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"MSAdSDKVideo"}],"externalID":"c:@M@MSAdSDKVideo@objc(cs)SDKSettings(py)clickAction"},"sections":[],"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/SDKSettings/clickAction":{"navigatorTitle":[{"text":"clickAction","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"clickAction","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MSAdSDKVideo@E@ClickAction","kind":"typeIdentifier","text":"ClickAction"}],"type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/clickAction","abstract":[{"text":"clickAction property allows publisher to define the behavior of the SDK when a user interacts with the ad. This property offers three distinct options, each of which defines how the SDK should handle the click-through URL associated with the ad.","type":"text"}],"title":"clickAction","url":"\/documentation\/msadsdkvideo\/sdksettings\/clickaction"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ClickAction":{"title":"ClickAction","abstract":[{"text":"ClickAction’s responsibility is to overseeing and responding to user interactions with Ad.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"ClickAction","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClickAction"}],"url":"\/documentation\/msadsdkvideo\/clickaction","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/SDKSettings":{"title":"SDKSettings","abstract":[{"text":"SDKSettings class is responsible for managing global settings for the SDK that are shared and common between multiple ad requests. It ensures consistency and ease of maintenance by allowing publishers to set these settings in one place, and the SDK uses these settings for all subsequent ad requests.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SDKSettings","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKSettings"}],"url":"\/documentation\/msadsdkvideo\/sdksettings","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"clickAction"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"clickAction"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction","text":"ClickAction","preciseIdentifier":"c:@M@MSAdSDKVideo@E@ClickAction"},{"kind":"text","text":" "},{"text":"clickAction","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings~1clickAction\/title","value":"clickAction"},{"value":[{"kind":"identifier","text":"clickAction"}],"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings~1clickAction\/fragments"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ClickAction\/title","op":"replace","value":"ClickAction"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ClickAction\/fragments","value":[{"text":"ClickAction","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings\/title","value":"SDKSettings","op":"replace"},{"op":"replace","value":[{"text":"SDKSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}