{"identifier":{"url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/customUserAgent","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings"]]},"metadata":{"role":"symbol","title":"customUserAgent","externalID":"c:@M@MSAdSDKVideo@objc(cs)SDKSettings(py)customUserAgent","navigatorTitle":[{"text":"customUserAgent","kind":"identifier"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"customUserAgent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","modules":[{"name":"MSAdSDKVideo"}]},"variants":[{"paths":["\/documentation\/msadsdkvideo\/sdksettings\/customuseragent"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/msadsdkvideo\/sdksettings\/customuseragent"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"customUserAgent property is a configuration option in an SDK that allows publishers to specify a custom User-Agent string for the SDK to use. By setting the property, publisher can override the User-Agent string that the SDK fetch from a WebView","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If a custom User-Agent string is provided (not nil), the SDK will use this provided string as the User-Agent for all HTTP requests made by the SDK."},{"type":"text","text":" "},{"type":"text","text":"Default Value: nil"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customUserAgent"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}]}],"kind":"symbol","references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/SDKSettings/customUserAgent":{"navigatorTitle":[{"kind":"identifier","text":"customUserAgent"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"customUserAgent"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/customUserAgent","abstract":[{"text":"customUserAgent property is a configuration option in an SDK that allows publishers to specify a custom User-Agent string for the SDK to use. By setting the property, publisher can override the User-Agent string that the SDK fetch from a WebView","type":"text"},{"text":" ","type":"text"},{"text":"If a custom User-Agent string is provided (not nil), the SDK will use this provided string as the User-Agent for all HTTP requests made by the SDK.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default Value: nil"}],"title":"customUserAgent","url":"\/documentation\/msadsdkvideo\/sdksettings\/customuseragent"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/SDKSettings":{"title":"SDKSettings","abstract":[{"text":"SDKSettings class is responsible for managing global settings for the SDK that are shared and common between multiple ad requests. It ensures consistency and ease of maintenance by allowing publishers to set these settings in one place, and the SDK uses these settings for all subsequent ad requests.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SDKSettings","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKSettings"}],"url":"\/documentation\/msadsdkvideo\/sdksettings","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"customUserAgent","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"customUserAgent"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"customUserAgent","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings~1customUserAgent\/title","value":"customUserAgent"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings~1customUserAgent\/fragments","value":[{"text":"customUserAgent","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings\/title","op":"replace","value":"SDKSettings"},{"value":[{"kind":"identifier","text":"SDKSettings"}],"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings\/fragments"}]}]}