{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/enableOpenMeasurement"},"abstract":[{"type":"text","text":"enableOpenMeasurement property determines whether the SDK should support Open Measurement for viewability and verification measurement when playing the ads. Open Measurement is a set of industry standards for measuring viewability and other ad-related metrics. By enabling Open Measurement, publishers and advertisers can ensure that ad viewability and verification measurements are conducted accurately and transparently."},{"text":" ","type":"text"},{"type":"text","text":"Default Value: true"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"enableOpenMeasurement","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/msadsdkvideo\/sdksettings\/enableopenmeasurement"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/msadsdkvideo\/sdksettings\/enableopenmeasurement"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings"]]},"metadata":{"modules":[{"name":"MSAdSDKVideo"}],"navigatorTitle":[{"kind":"identifier","text":"enableOpenMeasurement"}],"role":"symbol","title":"enableOpenMeasurement","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableOpenMeasurement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"externalID":"c:@M@MSAdSDKVideo@objc(cs)SDKSettings(py)enableOpenMeasurement"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/SDKSettings":{"title":"SDKSettings","abstract":[{"text":"SDKSettings class is responsible for managing global settings for the SDK that are shared and common between multiple ad requests. It ensures consistency and ease of maintenance by allowing publishers to set these settings in one place, and the SDK uses these settings for all subsequent ad requests.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SDKSettings","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKSettings"}],"url":"\/documentation\/msadsdkvideo\/sdksettings","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/SDKSettings/enableOpenMeasurement":{"navigatorTitle":[{"text":"enableOpenMeasurement","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableOpenMeasurement"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings\/enableOpenMeasurement","abstract":[{"text":"enableOpenMeasurement property determines whether the SDK should support Open Measurement for viewability and verification measurement when playing the ads. Open Measurement is a set of industry standards for measuring viewability and other ad-related metrics. By enabling Open Measurement, publishers and advertisers can ensure that ad viewability and verification measurements are conducted accurately and transparently.","type":"text"},{"text":" ","type":"text"},{"text":"Default Value: true","type":"text"}],"title":"enableOpenMeasurement","url":"\/documentation\/msadsdkvideo\/sdksettings\/enableopenmeasurement"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"enableOpenMeasurement"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"enableOpenMeasurement","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"kind":"text","text":", "},{"text":"unsafe_unretained","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableOpenMeasurement"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings\/title","value":"SDKSettings","op":"replace"},{"value":[{"kind":"identifier","text":"SDKSettings"}],"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings\/fragments"},{"value":"enableOpenMeasurement","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings~1enableOpenMeasurement\/title"},{"value":[{"kind":"identifier","text":"enableOpenMeasurement"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings~1enableOpenMeasurement\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}