{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd\/adResponseData"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/videoad\/adresponsedata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/msadsdkvideo\/videoad\/adresponsedata"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"adResponseData","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdResponseData","kind":"typeIdentifier","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)AdResponseData","text":"AdResponseData"},{"text":"? { get }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","title":"adResponseData","externalID":"c:@M@MSAdSDKVideo@objc(cs)VideoAd(py)adResponseData","navigatorTitle":[{"text":"adResponseData","kind":"identifier"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adResponseData","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)AdResponseData","text":"AdResponseData"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","modules":[{"name":"MSAdSDKVideo"}]},"abstract":[{"type":"text","text":"AdResponseData class is designed to encapsulate data related to ad responses, particularly for fetching ad content from a URL. This class provides properties for storing the URL of the ad content and any potential errors that may occur during the ad request and retrieval process."}],"kind":"symbol","references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAd/adResponseData":{"role":"symbol","abstract":[{"type":"text","text":"AdResponseData class is designed to encapsulate data related to ad responses, particularly for fetching ad content from a URL. This class provides properties for storing the URL of the ad content and any potential errors that may occur during the ad request and retrieval process."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adResponseData"},{"text":": ","kind":"text"},{"text":"AdResponseData","kind":"typeIdentifier","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)AdResponseData"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd\/adResponseData","navigatorTitle":[{"text":"adResponseData","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/videoad\/adresponsedata","title":"adResponseData","type":"topic","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAd":{"title":"VideoAd","abstract":[{"text":"VideoAd is allowing publisher to  request, load, and play video ads. VideoAd (Video Ad Request and Playback Handler) is responsible for handling video ad requests and facilitating their playback.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Primary responsibilities include Ad Request, Loading, Player Integration, Event Tracking,  Completion,  Caching and Ad Podding to play multiple Ad."}],"role":"symbol","navigatorTitle":[{"text":"VideoAd","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoAd"}],"url":"\/documentation\/msadsdkvideo\/videoad","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/AdResponseData":{"title":"AdResponseData","kind":"symbol","url":"\/documentation\/msadsdkvideo\/adresponsedata","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdResponseData"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"AdResponseData","kind":"identifier"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdResponseData","abstract":[{"type":"text","text":"AdResponseData class is designed to encapsulate data related to ad responses, particularly for fetching ad content from a URL. This class provides properties for storing the URL of the ad content and any potential errors that may occur during the ad request and retrieval process."}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"adResponseData","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"adResponseData","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdResponseData","kind":"typeIdentifier","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(cs)AdResponseData","text":"AdResponseData"},{"text":" * ","kind":"text"},{"text":"adResponseData","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"adResponseData","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd~1adResponseData\/title"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd~1adResponseData\/fragments","op":"replace","value":[{"text":"adResponseData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd\/title","op":"replace","value":"VideoAd"},{"value":[{"kind":"identifier","text":"VideoAd"}],"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd\/fragments"},{"value":"AdResponseData","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdResponseData\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AdResponseData"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdResponseData\/fragments","op":"replace"}]}]}