{"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadAd"},{"text":"(","kind":"text"},{"text":"loadDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MSAdSDKVideo@objc(pl)VideoAdLoadDelegate","text":"VideoAdLoadDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"loadAd(loadDelegate:)","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"loadAdWithLoadDelegate:"}],"externalID":"c:@M@MSAdSDKVideo@objc(cs)VideoAd(im)loadAdWithLoadDelegate:","modules":[{"name":"MSAdSDKVideo"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/videoad\/loadad(loaddelegate:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/msadsdkvideo\/videoad\/loadad(loaddelegate:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd"]]},"sections":[],"abstract":[{"text":"loadAd(loadDelegate:) method is used to initiate the loading of a video ad. This method sets a delegate object that conforms to the VideoAdLoadDelegate protocol to receive notifications and handle events related to the ad loading process.","type":"text"}],"identifier":{"url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd\/loadAd(loadDelegate:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"loadAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"loadDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"VideoAdLoadDelegate","kind":"typeIdentifier","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdLoadDelegate","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(pl)VideoAdLoadDelegate"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"An object that conforms to the VideoAdLoadDelegate protocol. This delegate object will receive notifications about the success or failure of the ad request."}],"type":"paragraph"}],"name":"loadDelegate:"}]}],"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAd":{"title":"VideoAd","abstract":[{"text":"VideoAd is allowing publisher to  request, load, and play video ads. VideoAd (Video Ad Request and Playback Handler) is responsible for handling video ad requests and facilitating their playback.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Primary responsibilities include Ad Request, Loading, Player Integration, Event Tracking,  Completion,  Caching and Ad Podding to play multiple Ad."}],"role":"symbol","navigatorTitle":[{"text":"VideoAd","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoAd"}],"url":"\/documentation\/msadsdkvideo\/videoad","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdLoadDelegate":{"navigatorTitle":[{"kind":"identifier","text":"VideoAdLoadDelegate"}],"type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoAdLoadDelegate","kind":"identifier"}],"role":"symbol","abstract":[{"text":"VideoAdLoadDelegate protocol defines methods that an object can implement to receive notifications and handle events related to video ad loading and requests. This protocol is typically used to establish a delegate relationship between an ad loading component and another object (such as a view controller) that wants to monitor and respond to ad request outcomes.","type":"text"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdLoadDelegate","title":"VideoAdLoadDelegate","url":"\/documentation\/msadsdkvideo\/videoadloaddelegate"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAd/loadAd(loadDelegate:)":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd\/loadAd(loadDelegate:)","type":"topic","abstract":[{"type":"text","text":"loadAd(loadDelegate:) method is used to initiate the loading of a video ad. This method sets a delegate object that conforms to the VideoAdLoadDelegate protocol to receive notifications and handle events related to the ad loading process."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadAd","kind":"identifier"},{"kind":"text","text":"("},{"text":"loadDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(pl)VideoAdLoadDelegate","text":"VideoAdLoadDelegate"},{"text":")","kind":"text"}],"url":"\/documentation\/msadsdkvideo\/videoad\/loadad(loaddelegate:)","role":"symbol","navigatorTitle":[{"text":"loadAdWithLoadDelegate:","kind":"identifier"}],"title":"loadAd(loadDelegate:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"loadAdWithLoadDelegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"loadAdWithLoadDelegate:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"loadAdWithLoadDelegate:"},{"kind":"text","text":"("},{"text":"id<VideoAdLoadDelegate>","preciseIdentifier":"c:Qo@M@MSAdSDKVideo@objc(pl)VideoAdLoadDelegate","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"loadDelegate"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd\/title","value":"VideoAd"},{"value":[{"text":"VideoAd","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdLoadDelegate\/title","value":"VideoAdLoadDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"VideoAdLoadDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdLoadDelegate\/fragments"},{"value":"loadAdWithLoadDelegate:","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd~1loadAd(loadDelegate:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadAdWithLoadDelegate:"}],"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd~1loadAd(loadDelegate:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}