{"hierarchy":{"paths":[["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd"]]},"sections":[],"abstract":[{"type":"text","text":"playAd(videoAdPlayerDelegate:adContainer:) method is used to play a previously loaded ad. It also includes a delegate that conforms to the VideoAdPlayDelegate protocol to handle ad playback callbacks."}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playAd","kind":"identifier"},{"kind":"text","text":"("},{"text":"videoAdPlayerDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VideoAdPlayDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(pl)VideoAdPlayDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"adContainer"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"modules":[{"name":"MSAdSDKVideo"}],"navigatorTitle":[{"text":"playAdWithVideoAdPlayerDelegate:adContainer:","kind":"identifier"}],"externalID":"c:@M@MSAdSDKVideo@objc(cs)VideoAd(im)playAdWithVideoAdPlayerDelegate:adContainer:","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","title":"playAd(videoAdPlayerDelegate:adContainer:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"playAd"},{"text":"(","kind":"text"},{"text":"videoAdPlayerDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"VideoAdPlayDelegate","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(pl)VideoAdPlayDelegate","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdPlayDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"adContainer"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo\/videoad\/playad(videoadplayerdelegate:adcontainer:)"]},{"paths":["\/documentation\/msadsdkvideo\/videoad\/playad(videoadplayerdelegate:adcontainer:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd\/playAd(videoAdPlayerDelegate:adContainer:)"},"references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAd/playAd(videoAdPlayerDelegate:adContainer:)":{"title":"playAd(videoAdPlayerDelegate:adContainer:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"playAd","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"videoAdPlayerDelegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"VideoAdPlayDelegate","preciseIdentifier":"c:@M@MSAdSDKVideo@objc(pl)VideoAdPlayDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"adContainer"},{"kind":"text","text":": "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"playAdWithVideoAdPlayerDelegate:adContainer:","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/videoad\/playad(videoadplayerdelegate:adcontainer:)","type":"topic","abstract":[{"text":"playAd(videoAdPlayerDelegate:adContainer:) method is used to play a previously loaded ad. It also includes a delegate that conforms to the VideoAdPlayDelegate protocol to handle ad playback callbacks.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd\/playAd(videoAdPlayerDelegate:adContainer:)"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAd":{"title":"VideoAd","abstract":[{"text":"VideoAd is allowing publisher to  request, load, and play video ads. VideoAd (Video Ad Request and Playback Handler) is responsible for handling video ad requests and facilitating their playback.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Primary responsibilities include Ad Request, Loading, Player Integration, Event Tracking,  Completion,  Caching and Ad Podding to play multiple Ad."}],"role":"symbol","navigatorTitle":[{"text":"VideoAd","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoAd"}],"url":"\/documentation\/msadsdkvideo\/videoad","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdPlayDelegate":{"title":"VideoAdPlayDelegate","abstract":[{"text":"VideoAdPlayDelegate protocol defines methods that an object can implement to receive and handle video ad playback events. This protocol is typically used to establish a delegate relationship between an ad playback component and another object (such as a view controller) that wants to monitor and respond to events during video ad playback.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"VideoAdPlayDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoAdPlayDelegate"}],"url":"\/documentation\/msadsdkvideo\/videoadplaydelegate","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdPlayDelegate","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"playAdWithVideoAdPlayerDelegate:adContainer:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"playAdWithVideoAdPlayerDelegate:adContainer:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"playAdWithVideoAdPlayerDelegate:"},{"kind":"text","text":"("},{"text":"id<VideoAdPlayDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@MSAdSDKVideo@objc(pl)VideoAdPlayDelegate"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"videoAdPlayerDelegate"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adContainer:"},{"text":"(","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"adContainer","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"playAdWithVideoAdPlayerDelegate:adContainer:","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd~1playAd(videoAdPlayerDelegate:adContainer:)\/title"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd~1playAd(videoAdPlayerDelegate:adContainer:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"playAdWithVideoAdPlayerDelegate:adContainer:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"VideoAd","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd\/title"},{"op":"replace","value":[{"text":"VideoAd","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd\/fragments"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdPlayDelegate\/title","op":"replace","value":"VideoAdPlayDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdPlayDelegate\/fragments","value":[{"kind":"identifier","text":"VideoAdPlayDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}