{"primaryContentSections":[{"content":[{"type":"heading","anchor":"Overview","level":2,"text":"Overview"}],"kind":"content"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/msadsdkvideo"]},{"paths":["\/documentation\/msadsdkvideo"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[[]]},"metadata":{"role":"collection","roleHeading":"Framework","title":"MSAdSDKVideo","externalID":"MSAdSDKVideo","modules":[{"name":"MSAdSDKVideo"}],"symbolKind":"module"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdResponseData","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdTagProperties","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/Logging","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSAdSDKInstream","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd"]},{"title":"Protocols","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdLoadDelegate","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdPlayDelegate"]},{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/sdkInitCompletion"],"title":"Type Aliases"},{"title":"Enumerations","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSInitialAudioSetting","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent"]}],"identifier":{"url":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/Logging":{"title":"Logging","abstract":[{"text":"Logging utility provides logging functionality that can be utilized across the SDK for the purpose of logging statements during debugging.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"Logging","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Logging"}],"url":"\/documentation\/msadsdkvideo\/logging","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/Logging","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdPlayDelegate":{"title":"VideoAdPlayDelegate","abstract":[{"text":"VideoAdPlayDelegate protocol defines methods that an object can implement to receive and handle video ad playback events. This protocol is typically used to establish a delegate relationship between an ad playback component and another object (such as a view controller) that wants to monitor and respond to events during video ad playback.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"VideoAdPlayDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoAdPlayDelegate"}],"url":"\/documentation\/msadsdkvideo\/videoadplaydelegate","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdPlayDelegate","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ClickAction":{"title":"ClickAction","abstract":[{"text":"ClickAction’s responsibility is to overseeing and responding to user interactions with Ad.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"ClickAction","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClickAction"}],"url":"\/documentation\/msadsdkvideo\/clickaction","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/SDKSettings":{"title":"SDKSettings","abstract":[{"text":"SDKSettings class is responsible for managing global settings for the SDK that are shared and common between multiple ad requests. It ensures consistency and ease of maintenance by allowing publishers to set these settings in one place, and the SDK uses these settings for all subsequent ad requests.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SDKSettings","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKSettings"}],"url":"\/documentation\/msadsdkvideo\/sdksettings","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/LogLevel":{"title":"LogLevel","abstract":[{"text":"LogLevel defines different log levels, each with an associated integer value for fine-tuned control over log verbosity.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"LogLevel","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"url":"\/documentation\/msadsdkvideo\/loglevel","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSInitialAudioSetting":{"title":"MSInitialAudioSetting","abstract":[{"text":"The initial audio setting options within a specific application","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"MSInitialAudioSetting","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MSInitialAudioSetting"}],"url":"\/documentation\/msadsdkvideo\/msinitialaudiosetting","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSInitialAudioSetting","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAd":{"title":"VideoAd","abstract":[{"text":"VideoAd is allowing publisher to  request, load, and play video ads. VideoAd (Video Ad Request and Playback Handler) is responsible for handling video ad requests and facilitating their playback.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Primary responsibilities include Ad Request, Loading, Player Integration, Event Tracking,  Completion,  Caching and Ad Podding to play multiple Ad."}],"role":"symbol","navigatorTitle":[{"text":"VideoAd","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoAd"}],"url":"\/documentation\/msadsdkvideo\/videoad","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/sdkInitCompletion":{"title":"sdkInitCompletion","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sdkInitCompletion"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdkInitCompletion"}],"url":"\/documentation\/msadsdkvideo\/sdkinitcompletion","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/sdkInitCompletion","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSAdSDKVideoVersionNumber":{"title":"MSAdSDKVideoVersionNumber","abstract":[{"text":"Project version number for MSAdSDKVideo.","type":"text"}],"role":"symbol","fragments":[{"text":"MSAdSDKVideoVersionNumber","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/msadsdkvideoversionnumber","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSAdSDKVideoVersionNumber","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdLoadDelegate":{"navigatorTitle":[{"kind":"identifier","text":"VideoAdLoadDelegate"}],"type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoAdLoadDelegate","kind":"identifier"}],"role":"symbol","abstract":[{"text":"VideoAdLoadDelegate protocol defines methods that an object can implement to receive notifications and handle events related to video ad loading and requests. This protocol is typically used to establish a delegate relationship between an ad loading component and another object (such as a view controller) that wants to monitor and respond to ad request outcomes.","type":"text"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdLoadDelegate","title":"VideoAdLoadDelegate","url":"\/documentation\/msadsdkvideo\/videoadloaddelegate"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/AdResponseData":{"title":"AdResponseData","kind":"symbol","url":"\/documentation\/msadsdkvideo\/adresponsedata","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdResponseData"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"AdResponseData","kind":"identifier"}],"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdResponseData","abstract":[{"type":"text","text":"AdResponseData class is designed to encapsulate data related to ad responses, particularly for fetching ad content from a URL. This class provides properties for storing the URL of the ad content and any potential errors that may occur during the ad request and retrieval process."}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSAdSDKInstream":{"title":"MSAdSDKInstream","abstract":[{"text":"MSAdSDKVideo  ensures that the sdk loads up with the required configuration like userAgent Network Manager","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"MSAdSDKInstream","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MSAdSDKInstream"}],"url":"\/documentation\/msadsdkvideo\/msadsdkinstream","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSAdSDKInstream","kind":"symbol"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/AdTagProperties":{"role":"symbol","title":"AdTagProperties","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdTagProperties","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdTagProperties"}],"navigatorTitle":[{"kind":"identifier","text":"AdTagProperties"}],"url":"\/documentation\/msadsdkvideo\/adtagproperties"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/AdEventData":{"role":"symbol","title":"AdEventData","type":"topic","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData","kind":"symbol","abstract":[{"text":"AdEventData class is designed to encapsulate essential information related to ad events and ad playback. It serves as a data structure to store data about the currently displayed ad, including its duration, position within a sequence, total ad count, click URL upon ad interaction, and any potential error that may occur during ad playback.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdEventData"}],"navigatorTitle":[{"text":"AdEventData","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/adeventdata"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSVideoPlayerSettings":{"abstract":[],"title":"MSVideoPlayerSettings","role":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings","url":"\/documentation\/msadsdkvideo\/msvideoplayersettings","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MSVideoPlayerSettings","kind":"identifier"}],"navigatorTitle":[{"text":"MSVideoPlayerSettings","kind":"identifier"}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/VideoAdEvent":{"abstract":[],"title":"VideoAdEvent","role":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent","url":"\/documentation\/msadsdkvideo\/videoadevent","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoAdEvent","kind":"identifier"}],"navigatorTitle":[{"text":"VideoAdEvent","kind":"identifier"}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo":{"kind":"symbol","url":"\/documentation\/msadsdkvideo","type":"topic","title":"MSAdSDKVideo","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo","abstract":[],"role":"collection"},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/MSAdSDKVideoVersionString":{"abstract":[{"type":"text","text":"Project version string for MSAdSDKVideo."}],"title":"MSAdSDKVideoVersionString","role":"symbol","identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSAdSDKVideoVersionString","url":"\/documentation\/msadsdkvideo\/msadsdkvideoversionstring","type":"topic","kind":"symbol","fragments":[{"text":"MSAdSDKVideoVersionString","kind":"identifier"}]},"doc://com.ms.adsdkvideo.MSAdSDKVideo/documentation/MSAdSDKVideo/ErrorMessageConstant":{"identifier":"doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorMessageConstant"}],"type":"topic","title":"ErrorMessageConstant","abstract":[{"type":"text","text":"“ErrorMessageConstant” is an enumeration that serves as a list of constants responsible for managing error for Ad Request"}],"navigatorTitle":[{"text":"ErrorMessageConstant","kind":"identifier"}],"url":"\/documentation\/msadsdkvideo\/errormessageconstant"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdEventData","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdResponseData","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/AdTagProperties","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSAdSDKInstream","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSVideoPlayerSettings","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/SDKSettings","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAd"]},{"title":"Protocols","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdLoadDelegate","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdPlayDelegate"]},{"identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSAdSDKVideoVersionNumber","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/MSAdSDKVideoVersionString"],"title":"Variables"},{"title":"Enumerations","identifiers":["doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ClickAction","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/ErrorMessageConstant","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/LogLevel","doc:\/\/com.ms.adsdkvideo.MSAdSDKVideo\/documentation\/MSAdSDKVideo\/VideoAdEvent"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdPlayDelegate\/title","op":"replace","value":"VideoAdPlayDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdPlayDelegate\/fragments","value":[{"text":"VideoAdPlayDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ClickAction\/title","value":"ClickAction"},{"op":"replace","value":[{"kind":"identifier","text":"ClickAction"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ClickAction\/fragments"},{"value":"SDKSettings","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SDKSettings"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1SDKSettings\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel\/title","value":"LogLevel"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1LogLevel\/fragments","op":"replace","value":[{"kind":"identifier","text":"LogLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd\/title","value":"VideoAd"},{"value":[{"kind":"identifier","text":"VideoAd"}],"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAd\/fragments"},{"value":"VideoAdLoadDelegate","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdLoadDelegate\/title"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdLoadDelegate\/fragments","value":[{"text":"VideoAdLoadDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdResponseData\/title","value":"AdResponseData"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdResponseData\/fragments","op":"replace","value":[{"text":"AdResponseData","kind":"identifier"}]},{"value":"MSAdSDKInstream","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1MSAdSDKInstream\/title"},{"op":"replace","value":[{"text":"MSAdSDKInstream","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1MSAdSDKInstream\/fragments"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdTagProperties\/title","op":"replace","value":"AdTagProperties"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdTagProperties\/fragments","value":[{"kind":"identifier","text":"AdTagProperties"}]},{"value":"AdEventData","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdEventData\/title"},{"value":[{"kind":"identifier","text":"AdEventData"}],"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1AdEventData\/fragments"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1MSVideoPlayerSettings\/title","value":"MSVideoPlayerSettings","op":"replace"},{"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1MSVideoPlayerSettings\/fragments","op":"replace","value":[{"text":"MSVideoPlayerSettings","kind":"identifier"}]},{"value":"VideoAdEvent","op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent\/title"},{"value":[{"text":"VideoAdEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1VideoAdEvent\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant\/title","value":"ErrorMessageConstant"},{"op":"replace","value":[{"kind":"identifier","text":"ErrorMessageConstant"}],"path":"\/references\/doc:~1~1com.ms.adsdkvideo.MSAdSDKVideo~1documentation~1MSAdSDKVideo~1ErrorMessageConstant\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}